with de_duplicacion_vtacatagentewt as (
	select
		_airbyte_raw_id,
		_airbyte_extracted_at,
		_airbyte_meta,
		nss,
		email,
		orden,
		clacup,
		clazona,
		fechains,
		claagente,
		idusuario,
		nomagente,
		bajalogica,
		motivobaja,
		nombrepcmod,
		_ab_cdc_lsn,
		clacuentacup,
		salesforceid,
		telefonocasa,
		clatipoagente,
		clausuariomod,
		escomisionista,
		fechaultimamod,
		_ab_cdc_cursor,
		apellidomaterno,
		apellidopaterno,
		claagentelegacy,
		fechabajalogica,
		idusuarioportal,
		telefonocelular,
		clatipoagentecuota,
		espagoporproveedor,
		_ab_cdc_deleted_at,
		_ab_cdc_updated_at,
		_ab_cdc_event_serial_no,
        ((LTRIM(RTRIM(nomagente))) || ' ' || (LTRIM(RTRIM(apellidomaterno))) || ' ' || (LTRIM(RTRIM(apellidopaterno)))) AS nomagentecompleto
		from {{ ref ('stg__vta_cat_agente_wt') }}
)
select
	*
from
	de_duplicacion_vtacatagentewt