with stg_cupcatproveedor as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_cupcatproveedor,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`dpp` as FLOAT64) as dpp,
		safe_cast(`rfc` as STRING) as rfc,
		safe_cast(`curp` as STRING) as curp,
		safe_cast(`calle` as STRING) as calle,
		safe_cast(`noext` as STRING) as noext,
		safe_cast(`noint` as STRING) as noint,
		safe_cast(`clacup` as INT64) as clacup,
		safe_cast(`claiva` as INT64) as claiva,
		upper(safe_cast(`nomcup` as STRING)) as nomcup,
		safe_cast(`clavecup` as INT64) as clavecup,
		safe_cast(`diaspago` as STRING) as diaspago,
		safe_cast(`telefono` as STRING) as telefono,
		safe_cast(`apmaterno` as STRING) as apmaterno,
		safe_cast(`appaterno` as STRING) as appaterno,
		safe_cast(`fechaalta` as DATETIME) as fechaalta,
		safe_cast(`plazopago` as INT64) as plazopago,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clapaiscon` as INT64) as clapaiscon,
		safe_cast(`esrevisado` as INT64) as esrevisado,
		safe_cast(`nomcontacto` as STRING) as nomcontacto,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`claestadocon` as INT64) as claestadocon,
		safe_cast(`codigopostal` as STRING) as codigopostal,
		safe_cast(`esextranjero` as INT64) as esextranjero,
		safe_cast(`requiere1099` as INT64) as requiere1099,
		safe_cast(`clacoloniacon` as INT64) as clacoloniacon,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`emailcontacto` as STRING) as emailcontacto,
		safe_cast(`clatiponegocio` as INT64) as clatiponegocio,
		safe_cast(`clatipopersona` as INT64) as clatipopersona,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`idautorizacion` as INT64) as idautorizacion,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`clamunicipiocon` as INT64) as clamunicipiocon,
		safe_cast(`clanacionalidad` as INT64) as clanacionalidad,
		safe_cast(`esautorizadosat` as INT64) as esautorizadosat,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`clatipoproveedor` as INT64) as clatipoproveedor,
		safe_cast(`esprimeramanousa` as INT64) as esprimeramanousa,
		safe_cast(`telefonocontacto` as STRING) as telefonocontacto,
		safe_cast(`direccioncontacto` as STRING) as direccioncontacto,
		safe_cast(`responsablefiscal` as STRING) as responsablefiscal,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`claestatusproveedor` as INT64) as claestatusproveedor,
		safe_cast(`fechavalidacionfiscal` as DATETIME) as fechavalidacionfiscal,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`esmetodoconexioncombinado` as INT64) as esmetodoconexioncombinado,
		safe_cast(`claregimenincorporacionfiscal` as INT64) as claregimenincorporacionfiscal
	from {{source('src_prod_kraken_abt','dbo_CupCatProveedor')}}
)
select * from stg_cupcatproveedor