with stg_mtocatactividad as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_mtocatactividad,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`valpf` as FLOAT64) as valpf,
		safe_cast(`nvalor` as INT64) as nvalor,
		safe_cast(`claturno` as INT64) as claturno,
		safe_cast(`penrepsn` as INT64) as penrepsn,
		safe_cast(`claequipo` as INT64) as claequipo,
		safe_cast(`prioridad` as INT64) as prioridad,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`esderiesgo` as INT64) as esderiesgo,
		safe_cast(`noreplicar` as INT64) as noreplicar,
		safe_cast(`clagravedad` as INT64) as clagravedad,
		safe_cast(`clatipoplan` as INT64) as clatipoplan,
		safe_cast(`esmigracion` as INT64) as esmigracion,
		safe_cast(`esseguridad` as INT64) as esseguridad,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`claactividad` as INT64) as claactividad,
		safe_cast(`claubicacion` as INT64) as claubicacion,
		safe_cast(`fechadescgen` as DATETIME) as fechadescgen,
		safe_cast(`nomactividad` as STRING) as nomactividad,
		safe_cast(`cladisciplina` as INT64) as cladisciplina,
		safe_cast(`clafrecuencia` as INT64) as clafrecuencia,
		safe_cast(`clarcmfuncion` as INT64) as clarcmfuncion,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`esdocumentada` as INT64) as esdocumentada,
		safe_cast(`fechaultimaot` as DATETIME) as fechaultimaot,
		safe_cast(`nombrearchivo` as STRING) as nombrearchivo,
		safe_cast(`reqcertificar` as INT64) as reqcertificar,
		safe_cast(`disponibleguia` as INT64) as disponibleguia,
		safe_cast(`esagrupadormod` as INT64) as esagrupadormod,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`tiempoestimado` as FLOAT64) as tiempoestimado,
		safe_cast(`valoracumulado` as INT64) as valoracumulado,
		safe_cast(`valoroperacion` as INT64) as valoroperacion,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`actividadactual` as INT64) as actividadactual,
		safe_cast(`claactividadgen` as INT64) as claactividadgen,
		safe_cast(`claprobabilidad` as INT64) as claprobabilidad,
		safe_cast(`clarcmmodofalla` as INT64) as clarcmmodofalla,
		safe_cast(`escopiagenerico` as INT64) as escopiagenerico,
		safe_cast(`esgenericopadre` as INT64) as esgenericopadre,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`clafrecuenciaexp` as INT64) as clafrecuenciaexp,
		safe_cast(`clafuncionpuesto` as INT64) as clafuncionpuesto,
		safe_cast(`claprioridadraud` as INT64) as claprioridadraud,
		safe_cast(`extensionarchivo` as STRING) as extensionarchivo,
		safe_cast(`claactividadpadre` as INT64) as claactividadpadre,
		safe_cast(`clarcmfuncionfalla` as INT64) as clarcmfuncionfalla,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`claestatusactividad` as INT64) as claestatusactividad,
		safe_cast(`narefaccionmaterial` as INT64) as narefaccionmaterial,
		safe_cast(`requiereparomaquina` as INT64) as requiereparomaquina,
		safe_cast(`clanominaresponsable` as INT64) as clanominaresponsable,
		safe_cast(`clatipomantenimiento` as INT64) as clatipomantenimiento,
		safe_cast(`clafrecuenciaoriginal` as INT64) as clafrecuenciaoriginal,
		safe_cast(`esmigracionmodificado` as INT64) as esmigracionmodificado,
		safe_cast(`esactividadseleccionada` as INT64) as esactividadseleccionada,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`clatrabajadorresponsable` as INT64) as clatrabajadorresponsable
	from {{source('src_prod_kraken_abt','MtoSch_MtoCatActividad')}}
)
select * from stg_mtocatactividad