with stg_concatdireccion as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_concatdireccion,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`claarea` as INT64) as claarea,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`claempresa` as INT64) as claempresa,
		safe_cast(`comentario` as STRING) as comentario,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`cladireccion` as INT64) as cladireccion,
		safe_cast(`claubicacion` as INT64) as claubicacion,
		upper(safe_cast(`nomdireccion` as STRING)) as nomdireccion,
		safe_cast(`numdireccion` as STRING) as numdireccion,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`nomdireccion2` as STRING) as nomdireccion2,
		safe_cast(`nomdireccion3` as STRING) as nomdireccion3,
		safe_cast(`nomdireccion4` as STRING) as nomdireccion4,
		safe_cast(`nomdireccion5` as STRING) as nomdireccion5,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`claunidadnegocio` as INT64) as claunidadnegocio,
		safe_cast(`clausuariocaptura` as INT64) as clausuariocaptura,
		safe_cast(`clausuarioautoriza` as INT64) as clausuarioautoriza,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`clatipodireccioncrc` as INT64) as clatipodireccioncrc,
		safe_cast(`claestatuscatalogoopc` as INT64) as claestatuscatalogoopc,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_ConCatDireccion')}}
)
select * from stg_concatdireccion