with stg_vtacatagentewt as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_vtacatagentewt,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`nss` as STRING) as nss,
		safe_cast(`email` as STRING) as email,
		safe_cast(`orden` as INT64) as orden,
		safe_cast(`clacup` as INT64) as clacup,
		safe_cast(`clazona` as INT64) as clazona,
		safe_cast(`fechains` as DATETIME) as fechains,
		safe_cast(`claagente` as INT64) as claagente,
		safe_cast(`idusuario` as INT64) as idusuario,
		upper(safe_cast(`nomagente` as STRING)) as nomagente,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`motivobaja` as STRING) as motivobaja,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`clacuentacup` as INT64) as clacuentacup,
		safe_cast(`salesforceid` as INT64) as salesforceid,
		safe_cast(`telefonocasa` as STRING) as telefonocasa,
		safe_cast(`clatipoagente` as INT64) as clatipoagente,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`escomisionista` as INT64) as escomisionista,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		upper(safe_cast(`apellidomaterno` as STRING)) as apellidomaterno,
		upper(safe_cast(`apellidopaterno` as STRING)) as apellidopaterno,
		safe_cast(`claagentelegacy` as INT64) as claagentelegacy,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`idusuarioportal` as INT64) as idusuarioportal,
		safe_cast(`telefonocelular` as STRING) as telefonocelular,
		safe_cast(`clatipoagentecuota` as INT64) as clatipoagentecuota,
		safe_cast(`espagoporproveedor` as INT64) as espagoporproveedor,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_VtaCatAgenteWt')}}
)
select * from stg_vtacatagentewt