with stg_fiscatinformacionfiscalempresa as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_fiscatinformacionfiscalempresa,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`rfc` as STRING) as rfc,
		safe_cast(`telefono` as STRING) as telefono,
		safe_cast(`fechaalta` as DATETIME) as fechaalta,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`claempresa` as INT64) as claempresa,
		safe_cast(`clapaiscon` as INT64) as clapaiscon,
		safe_cast(`esnacional` as INT64) as esnacional,
		safe_cast(`entrecalles` as STRING) as entrecalles,
		safe_cast(`nombrecalle` as STRING) as nombrecalle,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`claestadocon` as INT64) as claestadocon,
		safe_cast(`codigopostal` as STRING) as codigopostal,
		safe_cast(`tipovialidad` as STRING) as tipovialidad,
		safe_cast(`clacoloniacon` as INT64) as clacoloniacon,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`numeroexterior` as STRING) as numeroexterior,
		safe_cast(`numerointerior` as STRING) as numerointerior,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`clamunicipiocon` as INT64) as clamunicipiocon,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`bancobeneficiario` as INT64) as bancobeneficiario,
		safe_cast(`correoelectronico` as STRING) as correoelectronico,
		safe_cast(`nombrerazonsocial` as STRING) as nombrerazonsocial,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`referenciaadicional` as STRING) as referenciaadicional,
		safe_cast(`claveactividadfiscal` as STRING) as claveactividadfiscal,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`clainformacionfiscalempresa` as INT64) as clainformacionfiscalempresa,
		safe_cast(`caracteristicadomiciliofiscal` as STRING) as caracteristicadomiciliofiscal
	from {{source('src_prod_kraken_abt','dbo_FisCatInformacionFiscalEmpresa')}}
)
select * from stg_fiscatinformacionfiscalempresa