with stg_vtacatconsignado as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_vtacatconsignado,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`calle` as STRING) as calle,
		safe_cast(`taxid` as STRING) as taxid,
		safe_cast(`cucsfid` as STRING) as cucsfid,
		safe_cast(`eslocal` as INT64) as eslocal,
		safe_cast(`espuela` as STRING) as espuela,
		safe_cast(`contacto` as STRING) as contacto,
		safe_cast(`fechaalta` as DATETIME) as fechaalta,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`cuentacsid` as STRING) as cuentacsid,
		safe_cast(`cuentasfid` as STRING) as cuentasfid,
		safe_cast(`entrecalles` as STRING) as entrecalles,
		upper(safe_cast(`nombrepcmod` as STRING)) as nombrepcmod,
		safe_cast(`numexterior` as STRING) as numexterior,
		safe_cast(`numinterior` as STRING) as numinterior,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`esautofleteo` as INT64) as esautofleteo,
		safe_cast(`notaembarque` as STRING) as notaembarque,
		safe_cast(`claconsignado` as INT64) as claconsignado,
		safe_cast(`clamotivobaja` as INT64) as clamotivobaja,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`esnocargariva` as INT64) as esnocargariva,
		safe_cast(`claciudadunico` as INT64) as claciudadunico,
		safe_cast(`claferroviaria` as INT64) as claferroviaria,
		safe_cast(`comentariobaja` as STRING) as comentariobaja,
		safe_cast(`consignadosfid` as STRING) as consignadosfid,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`claciudadlegacy` as INT64) as claciudadlegacy,
		safe_cast(`claclienteunico` as INT64) as claclienteunico,
		safe_cast(`clacodigopostal` as INT64) as clacodigopostal,
		safe_cast(`clacoloniaunico` as INT64) as clacoloniaunico,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`ladanotificante` as STRING) as ladanotificante,
		safe_cast(`clamedioembarque` as INT64) as clamedioembarque,
		safe_cast(`essiemprevigente` as INT64) as essiemprevigente,
		upper(safe_cast(`nombreconsignado` as STRING)) as nombreconsignado,
		safe_cast(`mc_consignado_id` as STRING) as mc_consignado_id,
		safe_cast(`correonotificante` as STRING) as correonotificante,
		upper(safe_cast(`nombrenotificante` as STRING)) as nombrenotificante,
		safe_cast(`esdomicilioenlegal` as INT64) as esdomicilioenlegal,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`codigopostalimprime` as STRING) as codigopostalimprime,
		safe_cast(`telefononotificante` as STRING) as telefononotificante,
		safe_cast(`claestatusconsignado` as INT64) as claestatusconsignado,
		safe_cast(`esgeneracargoimpuesto` as INT64) as esgeneracargoimpuesto,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`claveinternacionalnotificante` as STRING) as claveinternacionalnotificante
	from {{source('src_prod_kraken_abt','dbo_VtaCatConsignado')}}
)
select * from stg_vtacatconsignado