with stg_mswcatlocalidad as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_mswcatlocalidad,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`tipoi5` as INT64) as tipoi5,
		safe_cast(`clapais` as INT64) as clapais,
		safe_cast(`telefono` as INT64) as telefono,
		safe_cast(`claciudad` as INT64) as claciudad,
		safe_cast(`claestado` as INT64) as claestado,
		safe_cast(`direccion` as STRING) as direccion,
		safe_cast(`telefono2` as STRING) as telefono2,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`nomtercero` as STRING) as nomtercero,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`clalocalidad` as INT64) as clalocalidad,
		safe_cast(`codigopostal` as INT64) as codigopostal,
		safe_cast(`nomlocalidad` as STRING) as nomlocalidad,
		safe_cast(`telefonoloc2` as STRING) as telefonoloc2,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`tipolocalidad` as INT64) as tipolocalidad,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`clagpolocalidad` as INT64) as clagpolocalidad,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`cladeptocontable` as INT64) as cladeptocontable,
		safe_cast(`essumaexistencia` as INT64) as essumaexistencia,
		safe_cast(`claalmacendefault` as INT64) as claalmacendefault,
		safe_cast(`espermiteembarque` as INT64) as espermiteembarque,
		safe_cast(`nomlocalidadcorto` as STRING) as nomlocalidadcorto,
		safe_cast(`clalocalidadmaster` as INT64) as clalocalidadmaster,
		safe_cast(`claregionlocalidad` as INT64) as claregionlocalidad,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`eslocalidadtransfer` as INT64) as eslocalidadtransfer,
		safe_cast(`espermitedevolucion` as INT64) as espermitedevolucion,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','MSWSch_MSWCatLocalidad')}}
)
select * from stg_mswcatlocalidad