with stg_mtocatequipo as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_mtocatequipo,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`conats` as INT64) as conats,
		safe_cast(`conatt` as INT64) as conatt,
		safe_cast(`claarea` as INT64) as claarea,
		safe_cast(`noserie` as STRING) as noserie,
		safe_cast(`noaplica` as INT64) as noaplica,
		safe_cast(`vidautil` as FLOAT64) as vidautil,
		safe_cast(`claequipo` as INT64) as claequipo,
		safe_cast(`escritico` as INT64) as escritico,
		safe_cast(`nomequipo` as STRING) as nomequipo,
		safe_cast(`secuencia` as INT64) as secuencia,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clamaquina` as STRING) as clamaquina,
		safe_cast(`clasubarea` as INT64) as clasubarea,
		safe_cast(`esensamble` as INT64) as esensamble,
		safe_cast(`clagenerico` as INT64) as clagenerico,
		safe_cast(`fechacompra` as DATETIME) as fechacompra,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`cambiorutasn` as INT64) as cambiorutasn,
		safe_cast(`claubicacion` as INT64) as claubicacion,
		safe_cast(`nomapeopalsn` as BOOL) as nomapeopalsn,
		safe_cast(`claequipotipo` as INT64) as claequipotipo,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`observaciones` as STRING) as observaciones,
		safe_cast(`clagrupoequipo` as INT64) as clagrupoequipo,
		safe_cast(`consumoporhora` as INT64) as consumoporhora,
		safe_cast(`datosproveedor` as STRING) as datosproveedor,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`ordenhorometro` as INT64) as ordenhorometro,
		safe_cast(`valorreemplazo` as FLOAT64) as valorreemplazo,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`cladepartamento` as INT64) as cladepartamento,
		safe_cast(`clatipogarantia` as INT64) as clatipogarantia,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`claestatusequipo` as INT64) as claestatusequipo,
		safe_cast(`codigofabricante` as STRING) as codigofabricante,
		safe_cast(`controlcalidadsn` as BOOL) as controlcalidadsn,
		safe_cast(`fechafingarantia` as DATETIME) as fechafingarantia,
		safe_cast(`fechainstalacion` as DATETIME) as fechainstalacion,
		safe_cast(`claunidadmedidapi` as INT64) as claunidadmedidapi,
		safe_cast(`potenciainstalada` as INT64) as potenciainstalada,
		safe_cast(`claequipopertenece` as INT64) as claequipopertenece,
		safe_cast(`localizacionfisica` as STRING) as localizacionfisica,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`codigomantenimiento` as STRING) as codigomantenimiento,
		safe_cast(`esllevamotorizacion` as INT64) as esllevamotorizacion,
		safe_cast(`fechainiciogarantia` as DATETIME) as fechainiciogarantia,
		safe_cast(`clanominaresponsable` as INT64) as clanominaresponsable,
		safe_cast(`claempresaresponsable` as INT64) as claempresaresponsable,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`claalimentacionelectrica` as INT64) as claalimentacionelectrica,
		safe_cast(`clatrabajadorresponsable` as INT64) as clatrabajadorresponsable
	from {{source('src_prod_kraken_abt','MtoSch_MtoCatEquipo')}}
)
select * from stg_mtocatequipo