with stg_vtacatorganizacionwt as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_vtacatorganizacionwt,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`email` as STRING) as email,
		safe_cast(`nivel` as INT64) as nivel,
		safe_cast(`clazona` as INT64) as clazona,
		safe_cast(`idorden` as INT64) as idorden,
		safe_cast(`clagrupo` as INT64) as clagrupo,
		safe_cast(`fechains` as DATETIME) as fechains,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clagerencia` as INT64) as clagerencia,
		safe_cast(`clatipozona` as INT64) as clatipozona,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`cladireccion` as INT64) as cladireccion,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`nombretitular` as STRING) as nombretitular,
		safe_cast(`claflujocuenta` as INT64) as claflujocuenta,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`claorganizacion` as INT64) as claorganizacion,
		safe_cast(`clasubdireccion` as INT64) as clasubdireccion,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		UPPER(safe_cast(`nomorganizacion` as STRING)) as nomorganizacion,
		safe_cast(`telefonocelular` as STRING) as telefonocelular,
		safe_cast(`clausuariotitular` as INT64) as clausuariotitular,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`clagerenciaregional` as INT64) as clagerenciaregional,
		safe_cast(`claniveltopelistaprecio` as INT64) as claniveltopelistaprecio,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`claniveltopelistadescuento` as INT64) as claniveltopelistadescuento,
		safe_cast(`escuentaautorizacionrequerida` as INT64) as escuentaautorizacionrequerida
	from {{source('src_prod_kraken_abt','dbo_VtaCatOrganizacionWt')}}
)
select * from stg_vtacatorganizacionwt