with stg_carcatformapago as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_carcatformapago,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`boncwtcod` as FLOAT64) as boncwtcod,
		safe_cast(`escontado` as INT64) as escontado,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`utilizacod` as INT64) as utilizacod,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`pctdesctopp` as FLOAT64) as pctdesctopp,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`bontonvyacod` as FLOAT64) as bontonvyacod,
		safe_cast(`claformapago` as INT64) as claformapago,
		safe_cast(`escontadosat` as INT64) as escontadosat,
		upper(safe_cast(`nomformapago` as STRING)) as nomformapago,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`diasgraciacod` as INT64) as diasgraciacod,
		safe_cast(`diaslimitecod` as INT64) as diaslimitecod,
		safe_cast(`descextrasncod` as INT64) as descextrasncod,
		safe_cast(`escartacredito` as INT64) as escartacredito,
		safe_cast(`esincluirfacpp` as INT64) as esincluirfacpp,
		safe_cast(`esutilizafecha` as INT64) as esutilizafecha,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`diasplazonormal` as INT64) as diasplazonormal,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`pctbontonvyacod` as FLOAT64) as pctbontonvyacod,
		safe_cast(`pctdesctopppcod` as FLOAT64) as pctdesctopppcod,
		safe_cast(`claformapagosat` as INT64) as claformapagosat,
		safe_cast(`clamovcarteracod` as INT64) as clamovcarteracod,
		safe_cast(`clatipoestadistica` as INT64) as clatipoestadistica,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','CARSch_CarCatFormaPago')}}
)
select * from stg_carcatformapago