with stg_concatcrc as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_concatcrc,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`clacrc` as INT64) as clacrc,
		safe_cast(`numcrc` as STRING) as numcrc,
		safe_cast(`fechains` as DATETIME) as fechains,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clatipocrc` as INT64) as clatipocrc,
		safe_cast(`comentario` as STRING) as comentario,
		safe_cast(`clacrcpadre` as INT64) as clacrcpadre,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		upper(safe_cast(`nomcrcidioma1` as STRING)) as nomcrcidioma1,
		safe_cast(`nomcrcidioma2` as STRING) as nomcrcidioma2,
		safe_cast(`nomcrcidioma3` as STRING) as nomcrcidioma3,
		safe_cast(`nomcrcidioma4` as STRING) as nomcrcidioma4,
		safe_cast(`nomcrcidioma5` as STRING) as nomcrcidioma5,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`clausuariocaptura` as INT64) as clausuariocaptura,
		safe_cast(`esrequieregpoasig` as INT64) as esrequieregpoasig,
		safe_cast(`clausuarioautoriza` as INT64) as clausuarioautoriza,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`clatipodireccioncrc` as INT64) as clatipodireccioncrc,
		safe_cast(`claestatuscatalogoopc` as INT64) as claestatuscatalogoopc,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_ConCatCRC')}}
)
select * from stg_concatcrc