with stg_vtatraestatuscarteracliente2 as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_vtatraestatuscarteracliente2,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`clamoneda` as INT64) as clamoneda,
		safe_cast(`sobregiro` as FLOAT64) as sobregiro,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		ifnull(safe_cast(`estatusfinal` as INT64),-1) as estatusfinal,
		ifnull(safe_cast(`estatuspaso1` as INT64),-1) as estatuspaso1,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`limitecredito` as FLOAT64) as limitecredito,
		safe_cast(`porcsobregiro` as INT64) as porcsobregiro,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`importecartera` as FLOAT64) as importecartera,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`claclienteunico` as INT64) as claclienteunico,
		ifnull(safe_cast(`estatussobregiro` as INT64),-1) as estatussobregiro,
		safe_cast(`porcfactvencidas` as INT64) as porcfactvencidas,
		safe_cast(`claofertaservicio` as INT64) as claofertaservicio,
		safe_cast(`creditodisponible` as FLOAT64) as creditodisponible,
		ifnull(safe_cast(`estatusdiasatraso` as INT64),-1) as estatusdiasatraso,
		safe_cast(`tiene45diasatraso` as INT64) as tiene45diasatraso,
		ifnull(safe_cast(`estatusfinalmesant` as INT64),-1) as estatusfinalmesant,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		ifnull(safe_cast(`estatusfactvencidas` as INT64),-1) as estatusfactvencidas,
		ifnull(safe_cast(`estatusrecuperacion` as INT64),-1) as estatusrecuperacion,
		safe_cast(`importefactvencidas` as FLOAT64) as importefactvencidas,
		safe_cast(`tienecontadosatpend` as INT64) as tienecontadosatpend,
		safe_cast(`porcdiasatrasomesant` as INT64) as porcdiasatrasomesant,
		safe_cast(`porcrecuperacionmesant` as INT64) as porcrecuperacionmesant,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','VtaSch_VtaTraEstatusCarteraCliente2')}}
)
select * from stg_vtatraestatuscarteracliente2