with stg_pprocatproveedor as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_pprocatproveedor,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`clacup` as INT64) as clacup,
		safe_cast(`sitioweb` as STRING) as sitioweb,
		safe_cast(`clamoneda` as INT64) as clamoneda,
		safe_cast(`plazopago` as INT64) as plazopago,
		safe_cast(`antiguedad` as FLOAT64) as antiguedad,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`referencia` as STRING) as referencia,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`claagrupador` as INT64) as claagrupador,
		safe_cast(`claproveedor` as INT64) as claproveedor,
		safe_cast(`idusuarioaut` as INT64) as idusuarioaut,
		safe_cast(`capitalengiro` as FLOAT64) as capitalengiro,
		safe_cast(`capitalsocial` as FLOAT64) as capitalsocial,
		safe_cast(`claclasifprov` as INT64) as claclasifprov,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`fechaautoriza` as DATETIME) as fechaautoriza,
		safe_cast(`motivorechazo` as STRING) as motivorechazo,
		safe_cast(`ventasanuales` as FLOAT64) as ventasanuales,
		safe_cast(`clacalidadprov` as INT64) as clacalidadprov,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`numeropersonal` as INT64) as numeropersonal,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`contactodeacero` as STRING) as contactodeacero,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`claclasificacion` as INT64) as claclasificacion,
		safe_cast(`clagiroproveedor` as INT64) as clagiroproveedor,
		safe_cast(`clatipoactividad` as INT64) as clatipoactividad,
		safe_cast(`esautoinventario` as INT64) as esautoinventario,
		safe_cast(`antiguedaddeacero` as FLOAT64) as antiguedaddeacero,
		safe_cast(`esproveedordeacero` as INT64) as esproveedordeacero,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`claestatusproveedor` as INT64) as claestatusproveedor,
		safe_cast(`clientesprincipales` as STRING) as clientesprincipales,
		safe_cast(`comentariosespeciales` as STRING) as comentariosespeciales,
		safe_cast(`claespecializacionprov` as INT64) as claespecializacionprov,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','PproSch_PproCatProveedor')}}
)
select * from stg_pprocatproveedor