with stg_tescatcup as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_tescatcup,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`rfc` as STRING) as rfc,
		safe_cast(`curp` as STRING) as curp,
		safe_cast(`calle` as STRING) as calle,
		safe_cast(`noext` as STRING) as noext,
		safe_cast(`noint` as STRING) as noint,
		safe_cast(`clacup` as INT64) as clacup,
		safe_cast(`nombre` as STRING) as nombre,
		safe_cast(`clapais` as INT64) as clapais,
		safe_cast(`estatus` as INT64) as estatus,
		safe_cast(`diaspago` as STRING) as diaspago,
		safe_cast(`telefono` as STRING) as telefono,
		safe_cast(`apmaterno` as STRING) as apmaterno,
		safe_cast(`appaterno` as STRING) as appaterno,
		safe_cast(`claestado` as INT64) as claestado,
		safe_cast(`fechaalta` as DATETIME) as fechaalta,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clacolonia` as INT64) as clacolonia,
		safe_cast(`cuentamail` as STRING) as cuentamail,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`tipopersona` as INT64) as tipopersona,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`codigopostal` as STRING) as codigopostal,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`fechadonativo` as DATETIME) as fechadonativo,
		safe_cast(`autorizacheque` as INT64) as autorizacheque,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`vigenciacheque` as INT64) as vigenciacheque,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`clamunicipiodelegacion` as INT64) as clamunicipiodelegacion,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_TesCatCUP')}}
)
select * from stg_tescatcup