with stg_flecattransportista as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_flecattransportista,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`fax` as STRING) as fax,
		safe_cast(`web` as STRING) as web,
		safe_cast(`calle` as STRING) as calle,
		safe_cast(`clacup` as INT64) as clacup,
		safe_cast(`correo` as STRING) as correo,
		safe_cast(`clapais` as INT64) as clapais,
		safe_cast(`colonia` as STRING) as colonia,
		safe_cast(`porciva` as FLOAT64) as porciva,
		safe_cast(`porcdppp` as FLOAT64) as porcdppp,
		safe_cast(`claciudad` as INT64) as claciudad,
		safe_cast(`claestado` as INT64) as claestado,
		safe_cast(`direccion` as STRING) as direccion,
		safe_cast(`telefono1` as STRING) as telefono1,
		safe_cast(`telefono2` as STRING) as telefono2,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`esdedicado` as INT64) as esdedicado,
		safe_cast(`esnacional` as INT64) as esnacional,
		safe_cast(`abreviacion` as STRING) as abreviacion,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`clacuentacup` as INT64) as clacuentacup,
		safe_cast(`claformapago` as INT64) as claformapago,
		safe_cast(`claubicacion` as INT64) as claubicacion,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`esconcontrato` as INT64) as esconcontrato,
		safe_cast(`plazoparapago` as INT64) as plazoparapago,
		safe_cast(`porcretencion` as FLOAT64) as porcretencion,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`clabeneficiario` as INT64) as clabeneficiario,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`clatransportista` as INT64) as clatransportista,
		safe_cast(`nomtransportista` as STRING) as nomtransportista,
		safe_cast(`numtransportista` as INT64) as numtransportista,
		safe_cast(`esdescuentoglobal` as INT64) as esdescuentoglobal,
		safe_cast(`clagrupotransporte` as INT64) as clagrupotransporte,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`descuentoprontopago` as FLOAT64) as descuentoprontopago,
		safe_cast(`claestatustransportista` as INT64) as claestatustransportista,
		safe_cast(`escobroprimacombustible` as INT64) as escobroprimacombustible,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`porccobroprimacombustible` as FLOAT64) as porccobroprimacombustible
	from {{source('src_prod_kraken_abt','FleSch_FLECatTransportista')}}
)
select * from stg_flecattransportista