with stg_trrcatmedida as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_trrcatmedida,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`radio` as FLOAT64) as radio,
		safe_cast(`medida` as FLOAT64) as medida,
		safe_cast(`redondez` as FLOAT64) as redondez,
		safe_cast(`clamedida` as INT64) as clamedida,
		safe_cast(`desclarga` as STRING) as desclarga,
		safe_cast(`esentrada` as INT64) as esentrada,
		safe_cast(`pinajuste` as FLOAT64) as pinajuste,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clacliente` as INT64) as clacliente,
		safe_cast(`descmedida` as STRING) as descmedida,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`pinposprevio` as FLOAT64) as pinposprevio,
		safe_cast(`clamedidapaso` as INT64) as clamedidapaso,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`diametropicos` as FLOAT64) as diametropicos,
		safe_cast(`clatiporodillo` as INT64) as clatiporodillo,
		safe_cast(`diametroranura` as FLOAT64) as diametroranura,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`clatipoalambron` as INT64) as clatipoalambron,
		safe_cast(`distanciapicosa` as FLOAT64) as distanciapicosa,
		safe_cast(`excentpinajuste` as FLOAT64) as excentpinajuste,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`pincomprobacion` as FLOAT64) as pincomprobacion,
		safe_cast(`radiotolerancia` as FLOAT64) as radiotolerancia,
		safe_cast(`clacantidadpasos` as INT64) as clacantidadpasos,
		safe_cast(`holgurapinajuste` as FLOAT64) as holgurapinajuste,
		safe_cast(`clatipotecnologia` as INT64) as clatipotecnologia,
		safe_cast(`excentpinposprevio` as FLOAT64) as excentpinposprevio,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`clavelocidadmaquina` as INT64) as clavelocidadmaquina,
		safe_cast(`holgurapinposprevio` as FLOAT64) as holgurapinposprevio,
		safe_cast(`excentpincomprobacion` as FLOAT64) as excentpincomprobacion,
		safe_cast(`holgurapincomprobacion` as FLOAT64) as holgurapincomprobacion,
		safe_cast(`diametropicostolerancia` as FLOAT64) as diametropicostolerancia,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`diametroranuratolerancia` as FLOAT64) as diametroranuratolerancia
	from {{source('src_prod_kraken_abt','dbo_TrrCatMedida')}}
)
select * from stg_trrcatmedida