with stg_nomcattrabajador as (
	select
		{{ dbt_utils.generate_surrogate_key(['clatrabajador', 'clanomina', 'claubicacion', 'claempresa']) }} as pk_nomcattrabajador,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`cup` as STRING) as cup,
		safe_cast(`nss` as STRING) as nss,
		safe_cast(`rfc` as STRING) as rfc,
		safe_cast(`sexo` as STRING) as sexo,
		safe_cast(`cp_sat` as STRING) as cp_sat,
		safe_cast(`clacrc` as INT64) as clacrc,
		safe_cast(`claarea` as INT64) as claarea,
		safe_cast(`clajefe` as INT64) as clajefe,
		safe_cast(`clapais` as INT64) as clapais,
		safe_cast(`clabanco` as INT64) as clabanco,
		safe_cast(`esactivo` as INT64) as esactivo,
		safe_cast(`fechains` as DATETIME) as fechains,
		safe_cast(`telefono` as STRING) as telefono,
		safe_cast(`claestado` as INT64) as claestado,
		safe_cast(`clanomina` as INT64) as clanomina,
		safe_cast(`clapuesto` as INT64) as clapuesto,
		safe_cast(`codpostal` as STRING) as codpostal,
		safe_cast(`direccion` as STRING) as direccion,
		safe_cast(`estadoisn` as INT64) as estadoisn,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clacolonia` as INT64) as clacolonia,
		safe_cast(`claempresa` as INT64) as claempresa,
		safe_cast(`claentidad` as STRING) as claentidad,
		safe_cast(`clajefeeun` as INT64) as clajefeeun,
		safe_cast(`claliqimss` as INT64) as claliqimss,
		safe_cast(`clacriterio` as INT64) as clacriterio,
		safe_cast(`gruposeguro` as STRING) as gruposeguro,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`clamunicipio` as INT64) as clamunicipio,
		safe_cast(`claubicacion` as INT64) as claubicacion,
		safe_cast(`fechaingreso` as DATETIME) as fechaingreso,
		safe_cast(`numerocuenta` as STRING) as numerocuenta,
		safe_cast(`clatrabajador` as INT64) as clatrabajador,
		safe_cast(`clausuarioins` as INT64) as clausuarioins,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`salariodiario` as FLOAT64) as salariodiario,
		safe_cast(`claestadocivil` as INT64) as claestadocivil,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		upper(safe_cast(`apellidomaterno` as STRING)) as apellidomaterno,
		upper(safe_cast(`apellidopaterno` as STRING)) as apellidopaterno,
		safe_cast(`cladepartamento` as INT64) as cladepartamento,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`fechanacimiento` as DATETIME) as fechanacimiento,
		safe_cast(`clatrabajadoreun` as INT64) as clatrabajadoreun,
		upper(safe_cast(`nombretrabajador` as STRING)) as nombretrabajador,
		safe_cast(`clagrupoasignacion` as INT64) as clagrupoasignacion,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_NomCatTrabajador')}}
)
select * from stg_nomcattrabajador