with stg_concatagrupadorfinanciero as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_concatagrupadorfinanciero,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`orden` as INT64) as orden,
		safe_cast(`escapital` as INT64) as escapital,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`esactivototal` as INT64) as esactivototal,
		safe_cast(`esotrosgastos` as INT64) as esotrosgastos,
		safe_cast(`espasivototal` as INT64) as espasivototal,
		safe_cast(`esutilidadneta` as INT64) as esutilidadneta,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`formulaimporte` as INT64) as formulaimporte,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`esutilidadbruta` as INT64) as esutilidadbruta,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`esactivocirculante` as INT64) as esactivocirculante,
		safe_cast(`espasivocortoplazo` as INT64) as espasivocortoplazo,
		safe_cast(`espasivolargoplazo` as INT64) as espasivolargoplazo,
		safe_cast(`espasivomascapital` as INT64) as espasivomascapital,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`esresultadointegral` as INT64) as esresultadointegral,
		safe_cast(`esutilidadoperacion` as INT64) as esutilidadoperacion,
		safe_cast(`esactivonocirculante` as INT64) as esactivonocirculante,
		safe_cast(`estotalgastooperacion` as INT64) as estotalgastooperacion,
		safe_cast(`claagrupadorfinanciero` as INT64) as claagrupadorfinanciero,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`esutilidadantesimpuestos` as INT64) as esutilidadantesimpuestos,
		safe_cast(`esresultadofinanciamiento` as INT64) as esresultadofinanciamiento,
		upper(safe_cast(`nomagrupadorfinancieroidioma1` as STRING)) as nomagrupadorfinancieroidioma1,
		upper(safe_cast(`nomagrupadorfinancieroidioma2` as STRING)) as nomagrupadorfinancieroidioma2,
		upper(safe_cast(`nomagrupadorfinancieroidioma3` as STRING)) as nomagrupadorfinancieroidioma3,
		upper(safe_cast(`nomagrupadorfinancieroidioma4` as STRING)) as nomagrupadorfinancieroidioma4,
		upper(safe_cast(`nomagrupadorfinancieroidioma5` as STRING)) as nomagrupadorfinancieroidioma5
	from {{source('src_prod_kraken_abt','ConSch_ConCatAgrupadorFinanciero')}}
)
select * from stg_concatagrupadorfinanciero