with stg_pldcatpoliticainventariocablesenc as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_pldcatpoliticainventariocablesenc,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`cantidad` as FLOAT64) as cantidad,
		safe_cast(`claunidad` as INT64) as claunidad,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clafamilia` as INT64) as clafamilia,
		safe_cast(`claproducto` as INT64) as claproducto,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`claseleccion` as INT64) as claseleccion,
		safe_cast(`claubicacion` as INT64) as claubicacion,
		safe_cast(`clausuarioins` as INT64) as clausuarioins,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`numerounidades` as INT64) as numerounidades,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`comentariosfinal` as STRING) as comentariosfinal,
		safe_cast(`clatipoinventario` as INT64) as clatipoinventario,
		safe_cast(`clausuarioinicial` as INT64) as clausuarioinicial,
		safe_cast(`fechaaltapolitica` as DATETIME) as fechaaltapolitica,
		safe_cast(`fechafintemporada` as DATETIME) as fechafintemporada,
		safe_cast(`cantidadtotalfinal` as FLOAT64) as cantidadtotalfinal,
		safe_cast(`claestatuspolitica` as INT64) as claestatuspolitica,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`numerounidadesfinal` as INT64) as numerounidadesfinal,
		safe_cast(`clarazoncambioinvfinal` as INT64) as clarazoncambioinvfinal,
		safe_cast(`fechafintemporadafinal` as DATETIME) as fechafintemporadafinal,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`idpoliticainventariocables` as INT64) as idpoliticainventariocables,
		safe_cast(`claclasificacioninventariofinal` as INT64) as claclasificacioninventariofinal,
		safe_cast(`claclasificacioninventarioinicial` as INT64) as claclasificacioninventarioinicial
	from {{source('src_prod_kraken_abt','PLDSch_PldCatPoliticaInventarioCablesEnc')}}
)
select * from stg_pldcatpoliticainventariocablesenc