with stg_vtacatcliente as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_vtacatcliente,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`rfc` as STRING) as rfc,
		safe_cast(`colonia` as STRING) as colonia,
		safe_cast(`fechains` as DATETIME) as fechains,
		safe_cast(`telefono` as STRING) as telefono,
		safe_cast(`claciudad` as INT64) as claciudad,
		safe_cast(`clamoneda` as INT64) as clamoneda,
		safe_cast(`direccion` as STRING) as direccion,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clacliente` as INT64) as clacliente,
		safe_cast(`claempresa` as INT64) as claempresa,
		safe_cast(`zonapostal` as STRING) as zonapostal,
		safe_cast(`tipocliente` as INT64) as tipocliente,
		safe_cast(`tipopersona` as INT64) as tipopersona,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`estatuslegal` as INT64) as estatuslegal,
		safe_cast(`fechaaltareal` as DATETIME) as fechaaltareal,
		safe_cast(`nombrecliente` as STRING) as nombrecliente,
		safe_cast(`porcentajeiva` as FLOAT64) as porcentajeiva,
		safe_cast(`clatipocliente` as INT64) as clatipocliente,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`claorganizacion` as INT64) as claorganizacion,
		safe_cast(`fechaaltalogica` as DATETIME) as fechaaltalogica,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`claclasifcliente` as INT64) as claclasifcliente,
		safe_cast(`clagirocomercial` as INT64) as clagirocomercial,
		safe_cast(`clagiroindustria` as INT64) as clagiroindustria,
		safe_cast(`claclasifclientev` as INT64) as claclasifclientev,
		safe_cast(`clacargofinanciero` as FLOAT64) as clacargofinanciero,
		safe_cast(`numerocedulafiscal` as STRING) as numerocedulafiscal,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`claclienteagrupador` as INT64) as claclienteagrupador,
		safe_cast(`plazomallasalambres` as INT64) as plazomallasalambres,
		safe_cast(`plazovarillaalambron` as INT64) as plazovarillaalambron,
		safe_cast(`fechaultimanegociacion` as DATETIME) as fechaultimanegociacion,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`fechalimitecreditoactual` as DATETIME) as fechalimitecreditoactual,
		safe_cast(`importelimitecreditoactual` as FLOAT64) as importelimitecreditoactual
	from {{source('src_prod_kraken_abt','dbo_VtaCatCliente')}}
)
select * from stg_vtacatcliente