with stg_cmpcatproveedorreflocal as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_cmpcatproveedorreflocal,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`calle` as STRING) as calle,
		safe_cast(`clacup` as INT64) as clacup,
		safe_cast(`claiva` as INT64) as claiva,
		safe_cast(`nombre` as STRING) as nombre,
		safe_cast(`clapais` as INT64) as clapais,
		safe_cast(`esactivo` as INT64) as esactivo,
		safe_cast(`claestado` as INT64) as claestado,
		safe_cast(`plazopago` as INT64) as plazopago,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clacolonia` as INT64) as clacolonia,
		safe_cast(`claestatus` as INT64) as claestatus,
		safe_cast(`claincoterm` as INT64) as claincoterm,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`claformapago` as INT64) as claformapago,
		safe_cast(`clamunicipio` as INT64) as clamunicipio,
		safe_cast(`claproveedor` as INT64) as claproveedor,
		safe_cast(`claubicacion` as INT64) as claubicacion,
		safe_cast(`codigopostal` as STRING) as codigopostal,
		safe_cast(`espagocheque` as INT64) as espagocheque,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`espenalizable` as INT64) as espenalizable,
		safe_cast(`justificacion` as STRING) as justificacion,
		safe_cast(`clacalidadprov` as INT64) as clacalidadprov,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`numeroexterior` as STRING) as numeroexterior,
		safe_cast(`numerointerior` as STRING) as numerointerior,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`clacondicionpago` as INT64) as clacondicionpago,
		safe_cast(`clatipoproveedor` as INT64) as clatipoproveedor,
		safe_cast(`clatipocalendario` as INT64) as clatipocalendario,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`motivodesactivacion` as STRING) as motivodesactivacion,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`esgenerapedidosimportacion` as INT64) as esgenerapedidosimportacion
	from {{source('src_prod_kraken_abt','dbo_CmpCatProveedorRefLocal')}}
)
select * from stg_cmpcatproveedorreflocal