with stg_cat as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_cat,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`activo` as INT64) as activo,
		safe_cast(`desglose` as INT64) as desglose,
		safe_cast(`fecha_ins` as DATETIME) as fecha_ins,
		safe_cast(`nombre_pc` as STRING) as nombre_pc,
		safe_cast(`cla_evento` as INT64) as cla_evento,
		safe_cast(`cla_planta` as INT64) as cla_planta,
		safe_cast(`min_maximo` as FLOAT64) as min_maximo,
		safe_cast(`min_minimo` as FLOAT64) as min_minimo,
		safe_cast(`foliosincro` as INT64) as foliosincro,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`desc_evento` as STRING) as desc_evento,
		safe_cast(`sum_vac_vac` as BOOL) as sum_vac_vac,
		safe_cast(`cla_sub_area` as INT64) as cla_sub_area,
		safe_cast(`min_objetivo` as FLOAT64) as min_objetivo,
		safe_cast(`fecha_ult_mod` as DATETIME) as fecha_ult_mod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`cla_tipo_demora` as INT64) as cla_tipo_demora,
		safe_cast(`cla_tipo_tiempo` as INT64) as cla_tipo_tiempo,
		safe_cast(`cla_usuario_ins` as INT64) as cla_usuario_ins,
		safe_cast(`cla_usuario_mod` as INT64) as cla_usuario_mod,
		safe_cast(`cla_grupo_demora` as INT64) as cla_grupo_demora,
		safe_cast(`cla_origen_demora` as INT64) as cla_origen_demora,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`clave_automatizacion` as INT64) as clave_automatizacion,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_Pro_Evento_Cat')}}
)
select * from stg_cat