with stg_enecatmedidor as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_enecatmedidor,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`orden` as INT64) as orden,
		safe_cast(`factor` as FLOAT64) as factor,
		safe_cast(`formula` as STRING) as formula,
		safe_cast(`clatarifa` as INT64) as clatarifa,
		safe_cast(`esvirtual` as INT64) as esvirtual,
		safe_cast(`sefactura` as INT64) as sefactura,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clamedidor` as INT64) as clamedidor,
		safe_cast(`enpolizasn` as INT64) as enpolizasn,
		safe_cast(`nommedidor` as STRING) as nommedidor,
		safe_cast(`setarifica` as INT64) as setarifica,
		safe_cast(`clasubgrupo` as INT64) as clasubgrupo,
		safe_cast(`descformula` as STRING) as descformula,
		safe_cast(`descmedidor` as STRING) as descmedidor,
		safe_cast(`esservicios` as INT64) as esservicios,
		safe_cast(`idequipoplc` as INT64) as idequipoplc,
		safe_cast(`limitevalor` as FLOAT64) as limitevalor,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`cladireccion` as INT64) as cladireccion,
		safe_cast(`claproveedor` as INT64) as claproveedor,
		safe_cast(`claubicacion` as INT64) as claubicacion,
		safe_cast(`estolerancia` as INT64) as estolerancia,
		safe_cast(`claenergetico` as INT64) as claenergetico,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`esaplicalimite` as INT64) as esaplicalimite,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`objetivoindice` as FLOAT64) as objetivoindice,
		safe_cast(`porctolerancia` as INT64) as porctolerancia,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`clamedidorpadre` as INT64) as clamedidorpadre,
		safe_cast(`escalculaindice` as INT64) as escalculaindice,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`claautomatizacion` as INT64) as claautomatizacion,
		safe_cast(`clavealfanumerica` as STRING) as clavealfanumerica,
		safe_cast(`cladepartamentoluz` as INT64) as cladepartamentoluz,
		safe_cast(`clatipodispositivo` as INT64) as clatipodispositivo,
		safe_cast(`nommedidorterceros` as STRING) as nommedidorterceros,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`aplicademandamaxima` as INT64) as aplicademandamaxima,
		safe_cast(`claunidadrecoleccion` as INT64) as claunidadrecoleccion,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`porcperdidatransformacion` as INT64) as porcperdidatransformacion
	from {{source('src_prod_kraken_abt','EneSch_EneCatMedidor')}}
)
select * from stg_enecatmedidor