with stg_mswcatproveedor5 as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_mswcatproveedor5,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`fax` as STRING) as fax,
		safe_cast(`email` as STRING) as email,
		safe_cast(`taxid` as STRING) as taxid,
		safe_cast(`clacup` as INT64) as clacup,
		safe_cast(`texto1` as STRING) as texto1,
		safe_cast(`texto2` as STRING) as texto2,
		safe_cast(`texto3` as STRING) as texto3,
		safe_cast(`texto4` as STRING) as texto4,
		safe_cast(`texto5` as STRING) as texto5,
		safe_cast(`texto6` as STRING) as texto6,
		safe_cast(`clapais` as INT64) as clapais,
		safe_cast(`attnline` as STRING) as attnline,
		safe_cast(`memoline` as STRING) as memoline,
		safe_cast(`telefono` as STRING) as telefono,
		safe_cast(`claciudad` as INT64) as claciudad,
		safe_cast(`claestado` as INT64) as claestado,
		safe_cast(`direccion` as STRING) as direccion,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`direccion2` as STRING) as direccion2,
		safe_cast(`strcdstzip` as STRING) as strcdstzip,
		safe_cast(`claformairs` as INT64) as claformairs,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`claformapago` as INT64) as claformapago,
		safe_cast(`claproveedor` as INT64) as claproveedor,
		safe_cast(`codigopostal` as STRING) as codigopostal,
		safe_cast(`estoolrepair` as INT64) as estoolrepair,
		safe_cast(`nomproveedor` as STRING) as nomproveedor,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`contactoadmin` as STRING) as contactoadmin,
		safe_cast(`esprovcompras` as INT64) as esprovcompras,
		safe_cast(`clatipopersona` as INT64) as clatipopersona,
		safe_cast(`claveproveedor` as STRING) as claveproveedor,
		safe_cast(`contactocompra` as STRING) as contactocompra,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`apellidomaterno` as STRING) as apellidomaterno,
		safe_cast(`apellidopaterno` as STRING) as apellidopaterno,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`clacondicionpago` as INT64) as clacondicionpago,
		safe_cast(`telcontactoadmin` as STRING) as telcontactoadmin,
		safe_cast(`clacuentaanticipo` as INT64) as clacuentaanticipo,
		safe_cast(`claproveedorpadre` as INT64) as claproveedorpadre,
		safe_cast(`telcontactocompra` as STRING) as telcontactocompra,
		safe_cast(`emailcontactoadmin` as STRING) as emailcontactoadmin,
		safe_cast(`permiteparcialidad` as INT64) as permiteparcialidad,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`emailcontactocompra` as STRING) as emailcontactocompra,
		safe_cast(`descripciondefvoucher` as STRING) as descripciondefvoucher,
		safe_cast(`descripcionparacheque` as STRING) as descripcionparacheque,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','FESCH_MSWCatProveedor5')}}
)
select * from stg_mswcatproveedor5