with stg_mancatarticulodimension as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_mancatarticulodimension,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`multiplo` as INT64) as multiplo,
		safe_cast(`altomtsind` as FLOAT64) as altomtsind,
		safe_cast(`anchomtsind` as FLOAT64) as anchomtsind,
		safe_cast(`claarticulo` as INT64) as claarticulo,
		safe_cast(`comentarios` as STRING) as comentarios,
		safe_cast(`largomtsind` as FLOAT64) as largomtsind,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`altomtsagrup` as FLOAT64) as altomtsagrup,
		safe_cast(`clataraagrup` as INT64) as clataraagrup,
		safe_cast(`empaqueagrup` as FLOAT64) as empaqueagrup,
		safe_cast(`anchomtsagrup` as FLOAT64) as anchomtsagrup,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`largomtsagrup` as FLOAT64) as largomtsagrup,
		safe_cast(`camanivelagrup` as FLOAT64) as camanivelagrup,
		safe_cast(`diametromtsind` as FLOAT64) as diametromtsind,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`pesotarakgsind` as FLOAT64) as pesotarakgsind,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`cantidadminagrup` as INT64) as cantidadminagrup,
		safe_cast(`diametromtsagrup` as FLOAT64) as diametromtsagrup,
		safe_cast(`numestibajeagrup` as INT64) as numestibajeagrup,
		safe_cast(`pesotarakgsagrup` as FLOAT64) as pesotarakgsagrup,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_ManCatArticuloDimension')}}
)
select * from stg_mancatarticulodimension