with stg_ffcccatferroviaria as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_ffcccatferroviaria,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`abrev` as STRING) as abrev,
		safe_cast(`email` as STRING) as email,
		safe_cast(`esactivo` as INT64) as esactivo,
		safe_cast(`escredito` as INT64) as escredito,
		safe_cast(`fechaalta` as DATETIME) as fechaalta,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`usuarioftp` as STRING) as usuarioftp,
		safe_cast(`costodemora` as FLOAT64) as costodemora,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`passwordftp` as STRING) as passwordftp,
		safe_cast(`tienecarros` as INT64) as tienecarros,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`direccionftp` as STRING) as direccionftp,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`numerocliente` as STRING) as numerocliente,
		safe_cast(`claferroviaria` as INT64) as claferroviaria,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`contactoanteffcc` as STRING) as contactoanteffcc,
		safe_cast(`costoderechopiso` as FLOAT64) as costoderechopiso,
		safe_cast(`claavisoproblemas` as INT64) as claavisoproblemas,
		safe_cast(`estraficonacional` as INT64) as estraficonacional,
		safe_cast(`horaslimitedemora` as INT64) as horaslimitedemora,
		safe_cast(`portalferroviaria` as STRING) as portalferroviaria,
		safe_cast(`claavisoliberacion` as INT64) as claavisoliberacion,
		safe_cast(`diasantessolicitud` as INT64) as diasantessolicitud,
		safe_cast(`horacortedemorafin` as INT64) as horacortedemorafin,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`aplicareutilizacion` as INT64) as aplicareutilizacion,
		safe_cast(`porcentajedescuento` as FLOAT64) as porcentajedescuento,
		safe_cast(`clamedioconfirmacion` as INT64) as clamedioconfirmacion,
		safe_cast(`escomunicacioncorreo` as INT64) as escomunicacioncorreo,
		safe_cast(`horaslimitereutiliza` as INT64) as horaslimitereutiliza,
		safe_cast(`claavisodocumentacion` as INT64) as claavisodocumentacion,
		safe_cast(`claavisoreutilizacion` as INT64) as claavisoreutilizacion,
		safe_cast(`horacortedemorainicio` as INT64) as horacortedemorainicio,
		safe_cast(`claavisoconfirmalibera` as INT64) as claavisoconfirmalibera,
		safe_cast(`claavisootrosservicios` as INT64) as claavisootrosservicios,
		safe_cast(`claavisorechazofactura` as INT64) as claavisorechazofactura,
		safe_cast(`nombrecortoferroviaria` as STRING) as nombrecortoferroviaria,
		safe_cast(`claavisoserviciocliente` as INT64) as claavisoserviciocliente,
		safe_cast(`claavisoserviciodiverso` as INT64) as claavisoserviciodiverso,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`claavisoasignacioncarros` as INT64) as claavisoasignacioncarros,
		safe_cast(`claavisoasignacionpedido` as INT64) as claavisoasignacionpedido,
		safe_cast(`claavisoconfirmadocumenta` as INT64) as claavisoconfirmadocumenta,
		safe_cast(`claavisoconfirmareutiliza` as INT64) as claavisoconfirmareutiliza,
		safe_cast(`claavisosolicitudasignacion` as INT64) as claavisosolicitudasignacion,
		safe_cast(`esoperacionserviciosporsistema` as INT64) as esoperacionserviciosporsistema,
		safe_cast(`claavisoconfirmaserviciodiverso` as INT64) as claavisoconfirmaserviciodiverso,
		safe_cast(`claavisoconfirmaprefacturafletes` as INT64) as claavisoconfirmaprefacturafletes,
		safe_cast(`claavisoconfirmaprefacturademoras` as INT64) as claavisoconfirmaprefacturademoras
	from {{source('src_prod_kraken_abt','dbo_FfccCatFerroviaria')}}
)
select * from stg_ffcccatferroviaria