with stg_ffcccatruta as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_ffcccatruta,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`kms` as FLOAT64) as kms,
		safe_cast(`tramo` as STRING) as tramo,
		safe_cast(`claruta` as INT64) as claruta,
		safe_cast(`esactivo` as INT64) as esactivo,
		safe_cast(`claorigen` as INT64) as claorigen,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`cladestino` as INT64) as cladestino,
		safe_cast(`nombreruta` as STRING) as nombreruta,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`espagaorigen` as INT64) as espagaorigen,
		safe_cast(`claconsignado` as INT64) as claconsignado,
		safe_cast(`claotraaduana` as INT64) as claotraaduana,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`observaciones` as STRING) as observaciones,
		safe_cast(`pesopermitido` as FLOAT64) as pesopermitido,
		safe_cast(`clapropietario` as INT64) as clapropietario,
		safe_cast(`clatipodestino` as INT64) as clatipodestino,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`pesotolerancia` as FLOAT64) as pesotolerancia,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`claclasetrafico` as INT64) as claclasetrafico,
		safe_cast(`clareconsignado` as INT64) as clareconsignado,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`clapagadororigen` as INT64) as clapagadororigen,
		safe_cast(`espesotolerancia` as INT64) as espesotolerancia,
		safe_cast(`claaduananacional` as INT64) as claaduananacional,
		safe_cast(`clacuptransloader` as INT64) as clacuptransloader,
		safe_cast(`claestacionorigen` as INT64) as claestacionorigen,
		safe_cast(`clapagadordestino` as INT64) as clapagadordestino,
		safe_cast(`claestaciondestino` as INT64) as claestaciondestino,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`esaplicatransloader` as INT64) as esaplicatransloader,
		safe_cast(`claproveedordescarga` as INT64) as claproveedordescarga,
		safe_cast(`claproveedortraslado` as INT64) as claproveedortraslado,
		safe_cast(`clatipodocumentacion` as INT64) as clatipodocumentacion,
		safe_cast(`claaduanainternacional` as INT64) as claaduanainternacional,
		safe_cast(`clatiposervtransloader` as INT64) as clatiposervtransloader,
		safe_cast(`clazonaviapuertaorigen` as INT64) as clazonaviapuertaorigen,
		safe_cast(`clapuntocontrolfrontera` as INT64) as clapuntocontrolfrontera,
		safe_cast(`clazonaviapuertadestino` as INT64) as clazonaviapuertadestino,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`esultferrocarrildelivery` as INT64) as esultferrocarrildelivery,
		safe_cast(`escambiaconsignadocliente` as INT64) as escambiaconsignadocliente
	from {{source('src_prod_kraken_abt','FFCCSch_FFCCCatRuta')}}
)
select * from stg_ffcccatruta