with stg_concatempresa as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_concatempresa,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`esjv` as INT64) as esjv,
		safe_cast(`fechains` as DATETIME) as fechains,
		--safe_cast(`logotipo` as STRING) as logotipo,
		safe_cast(`clamoneda` as INT64) as clamoneda,
		safe_cast(`esvigente` as INT64) as esvigente,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`claempresa` as INT64) as claempresa,
		safe_cast(`nomempresa` as STRING) as nomempresa,
		safe_cast(`basedatosgp` as STRING) as basedatosgp,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`nombasedatos` as STRING) as nombasedatos,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`claempresavtas` as INT64) as claempresavtas,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		upper(safe_cast(`nomcortoempresa` as STRING)) as nomcortoempresa,
		safe_cast(`esimportarsaldos` as INT64) as esimportarsaldos,
		safe_cast(`fechafinoperacion` as DATETIME) as fechafinoperacion,
		safe_cast(`ptjeparticipacion` as FLOAT64) as ptjeparticipacion,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`fechainiciooperacion` as DATETIME) as fechainiciooperacion,
		safe_cast(`clatipocuentacontable` as INT64) as clatipocuentacontable,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_ConCatEmpresa')}}
)
select * from stg_concatempresa