with stg_opecattma as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_opecattma,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`clatma` as INT64) as clatma,
		safe_cast(`nomtma` as STRING) as nomtma,
		safe_cast(`clavetma` as STRING) as clavetma,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`clagrupotma` as INT64) as clagrupotma,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`clagrupotma2` as INT64) as clagrupotma2,
		safe_cast(`clatmasalida` as INT64) as clatmasalida,
		safe_cast(`clatmaentrada` as INT64) as clatmaentrada,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`entradaosalida` as INT64) as entradaosalida,
		safe_cast(`escuentapuente` as INT64) as escuentapuente,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`clatmacontraparte` as INT64) as clatmacontraparte,
		safe_cast(`clatipoinventario` as INT64) as clatipoinventario,
		safe_cast(`significadotexto1` as STRING) as significadotexto1,
		safe_cast(`significadotexto2` as STRING) as significadotexto2,
		safe_cast(`afectacuentapuente` as INT64) as afectacuentapuente,
		safe_cast(`significadoentero1` as STRING) as significadoentero1,
		safe_cast(`significadoentero2` as STRING) as significadoentero2,
		safe_cast(`significadoentero3` as STRING) as significadoentero3,
		safe_cast(`significadoentero4` as STRING) as significadoentero4,
		safe_cast(`significadoentero5` as STRING) as significadoentero5,
		safe_cast(`significadoentero6` as STRING) as significadoentero6,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`esmercanciaentransito` as INT64) as esmercanciaentransito,
		safe_cast(`requierearticuloactivo` as INT64) as requierearticuloactivo,
		safe_cast(`claarticulocuentapuente` as INT64) as claarticulocuentapuente,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_OpeCatTMA')}}
)
select * from stg_opecattma