with stg_mswcatgrupoestadistico as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_mswcatgrupoestadistico,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`nivel01` as INT64) as nivel01,
		safe_cast(`nivel02` as INT64) as nivel02,
		safe_cast(`nivel03` as INT64) as nivel03,
		safe_cast(`nivel04` as INT64) as nivel04,
		safe_cast(`nivel05` as INT64) as nivel05,
		safe_cast(`nivel06` as INT64) as nivel06,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`nivelactual` as INT64) as nivelactual,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`fechacaptura` as DATETIME) as fechacaptura,
		safe_cast(`ordenalterno` as INT64) as ordenalterno,
		safe_cast(`clamargenventa` as INT64) as clamargenventa,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`clatipoproducto` as INT64) as clatipoproducto,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`clamargencomision` as INT64) as clamargencomision,
		safe_cast(`clatipoestadistico` as INT64) as clatipoestadistico,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`clagrupoestadistico` as INT64) as clagrupoestadistico,
		safe_cast(`nombregrupoestadistico` as STRING) as nombregrupoestadistico,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`nombregrupoestadisticocorto` as STRING) as nombregrupoestadisticocorto,
		safe_cast(`nombregrupoestadisticoingles` as STRING) as nombregrupoestadisticoingles
	from {{source('src_prod_kraken_abt','MSWSch_MswCatGrupoEstadistico')}}
)
select * from stg_mswcatgrupoestadistico