with stg_vtacatclienteagrupador as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_vtacatclienteagrupador,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`rfc` as STRING) as rfc,
		safe_cast(`colonia` as STRING) as colonia,
		safe_cast(`contacto` as STRING) as contacto,
		safe_cast(`fechains` as DATETIME) as fechains,
		safe_cast(`telefono` as STRING) as telefono,
		safe_cast(`claciudad` as INT64) as claciudad,
		safe_cast(`direccion` as STRING) as direccion,
		safe_cast(`fechaalta` as DATETIME) as fechaalta,
		safe_cast(`bajalogica` as INT64) as bajalogica,
		safe_cast(`zonapostal` as STRING) as zonapostal,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`fechaaltareal` as DATETIME) as fechaaltareal,
		safe_cast(`nombrecliente` as STRING) as nombrecliente,
		safe_cast(`clatipocliente` as INT64) as clatipocliente,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`claorganizacion` as INT64) as claorganizacion,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`claclasifcliente` as INT64) as claclasifcliente,
		safe_cast(`clagirocomercial` as INT64) as clagirocomercial,
		safe_cast(`clamedioembarque` as INT64) as clamedioembarque,
		safe_cast(`claclasifclientev` as INT64) as claclasifclientev,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`claclienteagrupador` as INT64) as claclienteagrupador,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no
	from {{source('src_prod_kraken_abt','dbo_VtaCatClienteAgrupador')}}
)
select * from stg_vtacatclienteagrupador