with stg_mtocatsubfamiliaensamble as (
	select
		--{{ dbt_utils.generate_surrogate_key(['col_pk1', 'col_pk2']) }} as pk_mtocatsubfamiliaensamble,
		safe_cast(`_airbyte_raw_id` as STRING) as _airbyte_raw_id,
		safe_cast(`_airbyte_extracted_at` as TIMESTAMP) as _airbyte_extracted_at,
		safe_cast(`_airbyte_meta` as JSON) as _airbyte_meta,
		safe_cast(`claequipo` as INT64) as claequipo,
		safe_cast(`bajalogica` as BOOL) as bajalogica,
		safe_cast(`esgenerica` as BOOL) as esgenerica,
		safe_cast(`hrsdesvest` as FLOAT64) as hrsdesvest,
		safe_cast(`cantidadmax` as INT64) as cantidadmax,
		safe_cast(`cantidadmin` as INT64) as cantidadmin,
		safe_cast(`hrsestandar` as FLOAT64) as hrsestandar,
		safe_cast(`hrspromedio` as FLOAT64) as hrspromedio,
		safe_cast(`nombrepcmod` as STRING) as nombrepcmod,
		safe_cast(`_ab_cdc_lsn` as STRING) as _ab_cdc_lsn,
		safe_cast(`claubicacion` as INT64) as claubicacion,
		safe_cast(`puntoreorden` as INT64) as puntoreorden,
		safe_cast(`clausuariomod` as INT64) as clausuariomod,
		safe_cast(`claresponsable` as INT64) as claresponsable,
		safe_cast(`fechaultimamod` as DATETIME) as fechaultimamod,
		safe_cast(`_ab_cdc_cursor` as INT64) as _ab_cdc_cursor,
		safe_cast(`cantidadrecurso` as INT64) as cantidadrecurso,
		safe_cast(`fechabajalogica` as DATETIME) as fechabajalogica,
		safe_cast(`cladeptocontable` as INT64) as cladeptocontable,
		safe_cast(`consumoanualprom` as FLOAT64) as consumoanualprom,
		safe_cast(`controlcalidadsn` as BOOL) as controlcalidadsn,
		safe_cast(`consumosimultaneo` as INT64) as consumosimultaneo,
		safe_cast(`claestaciontrabajo` as INT64) as claestaciontrabajo,
		safe_cast(`clafamiliaensamble` as INT64) as clafamiliaensamble,
		safe_cast(`_ab_cdc_deleted_at` as STRING) as _ab_cdc_deleted_at,
		safe_cast(`_ab_cdc_updated_at` as STRING) as _ab_cdc_updated_at,
		safe_cast(`clasubdeptocontable` as INT64) as clasubdeptocontable,
		safe_cast(`claubicacionalmacen` as INT64) as claubicacionalmacen,
		safe_cast(`consumoanualdesvest` as FLOAT64) as consumoanualdesvest,
		safe_cast(`clanominaresponsable` as INT64) as clanominaresponsable,
		safe_cast(`descripcionlocalidad` as STRING) as descripcionlocalidad,
		safe_cast(`clasubfamiliaensamble` as INT64) as clasubfamiliaensamble,
		safe_cast(`nomsubfamiliaensamble` as STRING) as nomsubfamiliaensamble,
		safe_cast(`clavesubfamiliaensamble` as STRING) as clavesubfamiliaensamble,
		safe_cast(`_ab_cdc_event_serial_no` as STRING) as _ab_cdc_event_serial_no,
		safe_cast(`clatipoinventarioensamble` as INT64) as clatipoinventarioensamble
	from {{source('src_prod_kraken_abt','MtoSch_MtoCatSubFamiliaEnsamble')}}
)
select * from stg_mtocatsubfamiliaensamble