{{ config(materialized='table') }}

{{ config(materialized='table') }}
WITH RAW_CAT_ARTICULO AS (
    SELECT
        A.CLATIPOINVENTARIO AS CLA_TIPO_INVENTARIO,
        A.CLAARTICULO AS CLA_PRODUCTO,
        A.CLAVEARTICULO AS CLAVE_ARTICULO,
        A.NOMARTICULO AS NOM_PRODUCTO,
        A.NOMARTICULOINGLES AS NOM_ARTICULO_INGLES,
        A.NOMARTICULOOTROIDIOMA AS NOM_ARTICULO_OTRO_IDIOMA,
        F.CLAFAMILIA AS CLA_FAMILIA,
        F.CLAVEFAMILIA AS CLAVE_FAMILIA,
        F.NOMFAMILIA AS NOM_FAMILIA,
        F.NOMFAMILIAINGLES AS NOM_FAMILIA_INGLES,
        SF.CLASUBFAMILIA AS CLA_SUBFAMILIA,
        SF.CLAVESUBFAMILIA AS CLAVE_SUBFAMILIA,
        SF.NOMSUBFAMILIA AS NOM_SUBFAMILIA,
        SF.NOMSUBFAMILIAINGLES AS NOM_SUBFAMILIA_INGLES,
        A.CLAMARCA AS CLA_MARCA,
        A.CLAGPOCOSTEO AS CLA_GPO_COSTEO,
        A.CLAGPOESTADISTICO AS CLA_GPO_ESTADISTICO,
        U.NOMUNIDAD AS NOM_UNIDAD,
        A.CLACLASIFGENERAL AS CLA_CLASIF_GENERAL,
        CG.NOMCLASIFGENERAL AS NOM_CLASIF_GENERAL,
        A.CLATIPOARTICULO AS CLA_TIPO_ARTICULO,
        TA.NOMTIPOARTICULO AS NOM_TIPO_ARTICULO,
        A.FECHAINS AS FECHA_ALTA,
        A.BAJALOGICA AS BAJA_LOGICA,
        A.FECHABAJALOGICA AS FECHA_BAJA_LOGICA,
        U.CLAUNIDAD AS CLA_UNIDAD,
        CASE
            WHEN G.NIVEL02 = 44
            THEN NULL
            ELSE A.PESOTEORICOKGS
        END AS PESO_TEORICO_KGS
    FROM {{ ref('stg__art_cat_articulo') }} AS A
    LEFT JOIN
        {{ ref('stg__vta_cat_grupo_estadistico') }} AS G
        ON A.CLAGPOESTADISTICO = G.CLAGRUPOESTADISTICO AND G.NIVELACTUAL = 4
    LEFT JOIN
        {{ ref('stg__art_cat_subfamilia') }} AS SF
        ON
            A.CLASUBFAMILIA = SF.CLASUBFAMILIA
            AND A.CLAFAMILIA = SF.CLAFAMILIA
            AND SF.CLATIPOINVENTARIO = 1
    LEFT JOIN
        {{ ref('stg__art_cat_familia') }} AS F
        ON SF.CLAFAMILIA = F.CLAFAMILIA AND F.CLATIPOINVENTARIO = 1
    LEFT JOIN
        {{ ref('stg__art_cat_unidad') }} AS U
        ON (U.CLAUNIDAD = A.CLAUNIDADBASE AND U.CLATIPOINVENTARIO = 1)
    LEFT JOIN
        {{ ref('stg__art_cat_clasif_general') }} AS CG
        ON
            (
                CG.CLACLASIFGENERAL = A.CLACLASIFGENERAL
                AND CG.CLATIPOINVENTARIO = 1
            )
    LEFT JOIN
        {{ ref('stg__art_cat_tipo_articulo') }} AS TA
        ON (TA.CLATIPOARTICULO = A.CLATIPOARTICULO AND TA.CLATIPOINVENTARIO = 1)
    WHERE A.CLATIPOINVENTARIO = 1
),

RAW_MSWCATARTICULO AS (
/*
    SELECT
    CLA_TIPO_INVENTARIO,
    CLA_PRODUCTO,
    CLAVE_ARTICULO,
    NOM_PRODUCTO,
    NOM_ARTICULO_INGLES,
    NOM_ARTICULO_OTRO_IDIOMA,
    CLA_FAMILIA,
    CLAVE_FAMILIA,
    NOM_FAMILIA,
    NOM_FAMILIA_INGLES,
    CLA_SUBFAMILIA,
    CLAVE_SUBFAMILIA,
    NOM_SUBFAMILIA,
    NOM_SUBFAMILIA_INGLES,
    CLA_MARCA,
    CLA_GPO_COSTEO,
    CLA_GPO_ESTADISTICO,
    PESO_TEORICO_KGS,
    CLA_UNIDAD,
    NOM_UNIDAD,
    CLA_CLASIF_GENERAL,
    NOM_CLASIF_GENERAL,
    CLA_TIPO_ARTICULO,
    NOM_TIPO_ARTICULO,
    FECHA_ALTA,
    BAJA_LOGICA,
    FECHA_BAJA_LOGICA
    FROM   RAW_CAT_ARTICULO
    UNION ALL
    */
    SELECT
        A.CLATIPOINVENTARIO AS CLA_TIPO_INVENTARIO,
        A.CLAARTICULO AS CLA_PRODUCTO,
        A.CLAVEARTICULO AS CLAVE_ARTICULO,
        A.NOMARTICULO AS NOM_PRODUCTO,
        A.NOMARTICULOINGLES AS NOM_ARTICULO_INGLES,
        A.NOMARTICULOOTROIDIOMA AS NOM_ARTICULO_OTRO_IDIOMA,
        F.CLAFAMILIA AS CLA_FAMILIA,
        F.CLAVEFAMILIA AS CLAVE_FAMILIA,
        F.NOMFAMILIA AS NOM_FAMILIA,
        F.NOMFAMILIAINGLES AS NOM_FAMILIA_INGLES,
        SF.CLASUBFAMILIA AS CLA_SUBFAMILIA,
        SF.CLAVESUBFAMILIA AS CLAVE_SUBFAMILIA,
        SF.NOMSUBFAMILIA AS NOM_SUBFAMILIA,
        SF.NOMSUBFAMILIAINGLES AS NOM_SUBFAMILIA_INGLES,
        A.CLAMARCA AS CLA_MARCA,
        NULL AS CLA_GPO_COSTEO,
        NULL AS CLA_GPO_ESTADISTICO,
        A.PESOTEORICOKGS AS PESO_TEORICO_KGS,
        NULL AS CLA_UNIDAD,
        '' AS NOM_UNIDAD,
        A.CLACLASIFGENERAL AS CLA_CLASIF_GENERAL,
        CG.NOMCLASIFGENERAL AS NOM_CLASIF_GENERAL,
        A.CLATIPOARTICULO AS CLA_TIPO_ARTICULO,
        TA.NOMTIPOARTICULO AS NOM_TIPO_ARTICULO,
        A.FECHAINS AS FECHA_ALTA,
        A.BAJALOGICA AS BAJA_LOGICA,
        A.FECHABAJALOGICA AS FECHA_BAJA_LOGICA
    FROM {{ ref('stg__msw_cat_articulo') }} AS A
    LEFT JOIN
        {{ ref('stg__art_cat_subfamilia') }} AS SF
        ON
            A.CLASUBFAMILIA = SF.CLASUBFAMILIA
            AND A.CLAFAMILIA = SF.CLAFAMILIA
            AND SF.CLATIPOINVENTARIO = 1
    LEFT JOIN
        {{ ref('stg__art_cat_familia') }} AS F
        ON SF.CLAFAMILIA = F.CLAFAMILIA AND F.CLATIPOINVENTARIO = 1
    LEFT JOIN
        {{ ref('stg__art_cat_clasif_general') }} AS CG
        ON
            (
                CG.CLACLASIFGENERAL = A.CLACLASIFGENERAL
                AND CG.CLATIPOINVENTARIO = 1
            )
    LEFT JOIN
        {{ ref('stg__art_cat_tipo_articulo') }} AS TA
        ON (TA.CLATIPOARTICULO = A.CLATIPOARTICULO AND TA.CLATIPOINVENTARIO = 1)
    WHERE
        A.CLATIPOINVENTARIO = 1
        AND A.CLAARTICULO NOT IN (SELECT CLA_PRODUCTO FROM RAW_CAT_ARTICULO)
),

RAW_CAT_ARTICULO_UNIFICADO AS (
    SELECT
        CLA_TIPO_INVENTARIO,
        CLA_PRODUCTO,
        CLAVE_ARTICULO,
        NOM_PRODUCTO,
        NOM_ARTICULO_INGLES,
        NOM_ARTICULO_OTRO_IDIOMA,
        CLA_FAMILIA,
        CLAVE_FAMILIA,
        NOM_FAMILIA,
        NOM_FAMILIA_INGLES,
        CLA_SUBFAMILIA,
        CLAVE_SUBFAMILIA,
        NOM_SUBFAMILIA,
        NOM_SUBFAMILIA_INGLES,
        CLA_MARCA,
        CLA_GPO_COSTEO,
        CLA_GPO_ESTADISTICO,
        PESO_TEORICO_KGS,
        CLA_UNIDAD,
        NOM_UNIDAD,
        CLA_CLASIF_GENERAL,
        NOM_CLASIF_GENERAL,
        CLA_TIPO_ARTICULO,
        NOM_TIPO_ARTICULO,
        FECHA_ALTA,
        BAJA_LOGICA,
        FECHA_BAJA_LOGICA
    FROM RAW_CAT_ARTICULO
    UNION ALL
    SELECT
        CLA_TIPO_INVENTARIO,
        CLA_PRODUCTO,
        CLAVE_ARTICULO,
        NOM_PRODUCTO,
        NOM_ARTICULO_INGLES,
        NOM_ARTICULO_OTRO_IDIOMA,
        CLA_FAMILIA,
        CLAVE_FAMILIA,
        NOM_FAMILIA,
        NOM_FAMILIA_INGLES,
        CLA_SUBFAMILIA,
        CLAVE_SUBFAMILIA,
        NOM_SUBFAMILIA,
        NOM_SUBFAMILIA_INGLES,
        CLA_MARCA,
        CLA_GPO_COSTEO,
        CLA_GPO_ESTADISTICO,
        PESO_TEORICO_KGS,
        CLA_UNIDAD,
        NOM_UNIDAD,
        CLA_CLASIF_GENERAL,
        NOM_CLASIF_GENERAL,
        CLA_TIPO_ARTICULO,
        NOM_TIPO_ARTICULO,
        FECHA_ALTA,
        BAJA_LOGICA,
        FECHA_BAJA_LOGICA
    FROM RAW_MSWCATARTICULO
),


RAW_CAT_GRUPO_ESTADISTICO AS (
    SELECT
        CLAGRUPOESTADISTICO AS CLA_GRUPO_ESTADISTICO,
        NIVELACTUAL AS NIVEL_ACTUAL,
        NOMBREGRUPOESTADISTICO AS NOM_GRUPO_ESTADISTICO,
        NOMBREGRUPOESTADISTICOINGLES AS NOM_GRUPO_ESTADISTICO_INGLES,
        NIVEL01,
        NIVEL02,
        NIVEL03,
        NIVEL04
    FROM {{ ref('stg__vta_cat_grupo_estadistico') }}
),

RAW_SEGMENTO AS (
    SELECT
        CFGSEG.CLAGRUPOESTADISTICO3 AS CLA_GRUPO_ESTADISTICO3,
        CFGSEG.CLAMARKETSEGMENT AS CLA_MARKET_SEGMENT,
        I.NOMMARKETSEGMENT AS NOM_MARKET_SEGMENT
    FROM {{ ref('int__dcp_msw_cfg_bsc_gpo_est_segmento') }} AS CFGSEG
    LEFT JOIN
        {{ ref('int__dcp_msw_cat_bsc_segmento') }} AS I
        ON I.CLASEGMENTO = CFGSEG.CLASEGMENTO
    LEFT JOIN
        {{ ref('stg__vta_cat_grupo_estadistico') }} AS GE
        ON
            GE.CLAGRUPOESTADISTICO = CFGSEG.CLAGRUPOESTADISTICO3
            AND GE.NIVELACTUAL = 3
    WHERE
        CFGSEG.CLAGRUPOESTADISTICO3 > 0
        AND CFGSEG.CLAMARKETSEGMENT IS NOT NULL
    GROUP BY
        CFGSEG.CLAGRUPOESTADISTICO3, CFGSEG.CLAMARKETSEGMENT, I.NOMMARKETSEGMENT
),

RAW_CAT_FAMILIA_ASOCIADA AS (
    SELECT
        CLAFAMILIAASOCIADA AS CLA_FAMILIA_ASOCIADA,
        NOMFAMILIAASOCIADA AS NOM_FAMILIA_ASOCIADA,
        IDFAMILIAASOCIADA AS ID_FAMILIA_ASOCIADA
    FROM {{ ref('int__dcp_pld_cat_familia_asociada') }}
    UNION ALL
    SELECT
        CLAFAMILIAASOCIADA AS CLA_FAMILIA_ASOCIADA,
        NOMFAMILIAASOCIADA AS NOM_FAMILIA_ASOCIADA,
        IDFAMILIAASOCIADA AS ID_FAMILIA_ASOCIADA
    FROM {{ ref('int__dcp_art_cat_familia') }}
    WHERE CLATIPOINVENTARIO = 1
),

RAW_REL_FAMILIA_ASOCIADA AS (
    SELECT
        R.CLAFAMILIAASOCIADA AS CLA_FAMILIA_ASOCIADA,
        R.CLAFAMILIA AS CLA_FAMILIA,
        R.CLASUBFAMILIA AS CLA_SUBFAMILIA,
        R.IDFAMILIAASOCIADA AS ID_FAMILIA_ASOCIADA
    FROM {{ ref('int__dcp_pld_rel_familia_asociada') }} AS R
    INNER JOIN
        {{ ref('int__dcp_pld_cat_familia_asociada') }} AS C
        ON R.CLAFAMILIAASOCIADA = C.CLAFAMILIAASOCIADA
    WHERE
        R.BAJALOGICA = 0
        AND C.BAJALOGICA = 0
),

RAW_REL_FAMILIA_AGRUPADOR AS (
    SELECT
        CLAFAMILIA AS CLA_FAMILIA,
        CLASUBFAMILIA AS CLA_SUBFAMILIA,
        CLAARTICULO AS CLA_ARTICULO,
        CLAFAMAGRUPADOR AS CLA_FAM_AGRUPADOR,
        CLAFAMAGRUPADORDET AS CLA_FAM_AGRUPADOR_DET,
        BAJALOGICA AS BAJA_LOGICA
    FROM {{ ref('stg__pld_rel_fam_agrupador') }}
),

RAW_CAT_FAMILIA_AGRUPADOR AS (
    SELECT
        CLAFAMAGRUPADOR AS CLA_FAMILIA_AGRUPADOR,
        DESCFAMAGRUPADOR AS NOM_FAMILIA_AGRUPADOR,
        BAJALOGICA AS BAJA_LOGICA
    FROM {{ ref('stg__pld_cat_fam_agrupador') }}
),

RAW_CAT_FAM_AGRUPADOR_DET AS (
    SELECT
        CLAFAMAGRUPADOR AS CLA_FAM_AGRUPADOR,
        CLAFAMAGRUPADORDET AS CLA_FAMILIA_AGRUPADOR_DET,
        DESCFAMAGRUPADORDET AS NOM_FAMILIA_AGRUPADOR_DET,
        BAJALOGICA AS BAJA_LOGICA
    FROM {{ ref('stg__pld_cat_fam_agrupador_det') }}
),

RAW_REL_MERCADO_INV AS (
    SELECT
        CLAMERCADOINV AS CLA_MERCADO_INV,
        CLAFAMILIA AS CLA_FAMILIA,
        CLASUBFAMILIA AS CLA_SUBFAMILIA,
        CLAPRODUCTO AS CLA_PRODUCTO,
        BAJALOGICA AS BAJA_LOGICA
    FROM {{ ref('stg__pld_rel_mercado_inv') }}
),

RAW_CAT_MERCADO_INV AS (
    SELECT
        CLAMERCADOINV AS CLA_MERCADO_INVENTARIO,
        NOMMERCADOINV AS NOM_MERCADO_INVENTARIO,
        BAJALOGICA AS BAJA_LOGICA
    FROM {{ ref('stg__pld_cat_mercado_inv') }}
),

RAW_REL_GPOEST_OFERTA_VALOR AS ( --Tabla para MAES
    SELECT
        Nivel as NIVEL,
        ClaGpoEst as CLA_GPO_EST,
        ClaOfertaValor as CLA_OFERTA_VALOR,
    FROM {{ ref('stg__vta_rel_gpoest_oferta_valor') }}
),

RAW_CAT_OFERTA_VALOR AS (  --Tabla para MAES
    SELECT
        ClaOfertaValor as CLA_OFERTA_VALOR,
        NomOfertaValor as NOM_OFERTA_VALOR,
    FROM {{ ref('stg__vta_cat_oferta_valor') }}
),


MST_PRODUCTO_VW AS (
    SELECT
        A.CLA_TIPO_INVENTARIO,
        A.CLA_PRODUCTO,
        A.CLAVE_ARTICULO,
        A.NOM_PRODUCTO,
        A.CLA_SUBFAMILIA,
        A.CLAVE_SUBFAMILIA,
        A.NOM_SUBFAMILIA,
        A.CLA_FAMILIA,
        A.CLAVE_FAMILIA,
        A.NOM_FAMILIA,
        GE1.CLA_GRUPO_ESTADISTICO AS CLA_GRUPO_ESTADISTICO1,
        GE1.NOM_GRUPO_ESTADISTICO AS NOM_GRUPO_ESTADISTICO1,
        GE1.NOM_GRUPO_ESTADISTICO_INGLES AS STATISTICAL_GROUP1,
        GE2.CLA_GRUPO_ESTADISTICO AS CLA_GRUPO_ESTADISTICO2,
        GE2.NOM_GRUPO_ESTADISTICO AS NOM_GRUPO_ESTADISTICO2,
        GE2.NOM_GRUPO_ESTADISTICO_INGLES AS STATISTICAL_GROUP2,
        GE3.CLA_GRUPO_ESTADISTICO AS CLA_GRUPO_ESTADISTICO3,
        GE3.NOM_GRUPO_ESTADISTICO AS NOM_GRUPO_ESTADISTICO3,
        GE3.NOM_GRUPO_ESTADISTICO_INGLES AS STATISTICAL_GROUP3,
        GE4.CLA_GRUPO_ESTADISTICO AS CLA_GRUPO_ESTADISTICO4,
        GE4.NOM_GRUPO_ESTADISTICO AS NOM_GRUPO_ESTADISTICO4,
        GE4.NOM_GRUPO_ESTADISTICO_INGLES AS STATISTICAL_GROUP4,
        A.NOM_UNIDAD,
        A.CLA_CLASIF_GENERAL,
        A.NOM_CLASIF_GENERAL,
        A.CLA_TIPO_ARTICULO,
        A.NOM_TIPO_ARTICULO,
        A.FECHA_ALTA,
        A.BAJA_LOGICA,
        FAS.ID_FAMILIA_ASOCIADA,
        FAS.NOM_FAMILIA_ASOCIADA,
        MS.CLA_MARKET_SEGMENT,
        MS.NOM_MARKET_SEGMENT,
        DESCFAE.CLA_FAMILIA_AGRUPADOR,
        DESCFAE.NOM_FAMILIA_AGRUPADOR,
        DESCFAD.CLA_FAMILIA_AGRUPADOR_DET,
        DESCFAD.NOM_FAMILIA_AGRUPADOR_DET,
        DESCRMI.CLA_MERCADO_INVENTARIO,
        DESCRMI.NOM_MERCADO_INVENTARIO,
        COALESCE(ROUND(A.PESO_TEORICO_KGS, 6), 1) AS PESO_TEORICO_KGS,
        CASE WHEN A.BAJA_LOGICA = 1 THEN A.FECHA_BAJA_LOGICA END
            AS FECHA_BAJA,
        OV.CLA_OFERTA_VALOR,
        OV.NOM_OFERTA_VALOR,

    FROM RAW_CAT_ARTICULO_UNIFICADO AS A
    LEFT JOIN
        RAW_CAT_GRUPO_ESTADISTICO AS GE4
        ON
            A.CLA_GPO_ESTADISTICO = GE4.CLA_GRUPO_ESTADISTICO
            AND GE4.NIVEL_ACTUAL = 4
    LEFT JOIN
        RAW_CAT_GRUPO_ESTADISTICO AS GE3
        ON GE4.NIVEL03 = GE3.CLA_GRUPO_ESTADISTICO AND GE3.NIVEL_ACTUAL = 3
    LEFT JOIN
        RAW_CAT_GRUPO_ESTADISTICO AS GE2
        ON GE3.NIVEL02 = GE2.CLA_GRUPO_ESTADISTICO AND GE2.NIVEL_ACTUAL = 2
    LEFT JOIN
        RAW_CAT_GRUPO_ESTADISTICO AS GE1
        ON GE2.NIVEL01 = GE1.CLA_GRUPO_ESTADISTICO AND GE1.NIVEL_ACTUAL = 1
    LEFT JOIN
        RAW_REL_FAMILIA_ASOCIADA AS FA
        ON
            A.CLA_FAMILIA = FA.CLA_FAMILIA
            AND A.CLA_SUBFAMILIA = FA.CLA_SUBFAMILIA
    LEFT JOIN
        RAW_CAT_FAMILIA_ASOCIADA AS FAS
        ON
            COALESCE(FA.ID_FAMILIA_ASOCIADA, 200000 + A.CLA_FAMILIA)
            = FAS.ID_FAMILIA_ASOCIADA
    LEFT JOIN
        RAW_REL_MERCADO_INV AS RMI1
        ON
            A.CLA_PRODUCTO = RMI1.CLA_PRODUCTO
            AND A.CLA_FAMILIA = RMI1.CLA_FAMILIA
            AND A.CLA_SUBFAMILIA = RMI1.CLA_SUBFAMILIA
            AND RMI1.BAJA_LOGICA = 0
    LEFT JOIN RAW_SEGMENTO AS MS ON GE4.NIVEL03 = MS.CLA_GRUPO_ESTADISTICO3
    LEFT JOIN
        RAW_REL_FAMILIA_AGRUPADOR AS RFA1
        ON
            A.CLA_PRODUCTO = RFA1.CLA_ARTICULO
            AND A.CLA_FAMILIA = RFA1.CLA_FAMILIA
            AND A.CLA_SUBFAMILIA = RFA1.CLA_SUBFAMILIA
            AND RFA1.BAJA_LOGICA = 0
    LEFT JOIN
        RAW_REL_FAMILIA_AGRUPADOR AS PRFA
        ON
            PRFA.BAJA_LOGICA = 0
            AND PRFA.CLA_ARTICULO > 0
            AND A.CLA_PRODUCTO = PRFA.CLA_ARTICULO
    LEFT JOIN
        RAW_REL_FAMILIA_AGRUPADOR AS PRFASF
        ON
            PRFASF.BAJA_LOGICA = 0
            AND PRFASF.CLA_ARTICULO <= 0
            AND PRFASF.CLA_SUBFAMILIA > 0
            AND A.CLA_SUBFAMILIA = PRFASF.CLA_SUBFAMILIA
            AND A.CLA_FAMILIA = PRFASF.CLA_FAMILIA
    LEFT JOIN
        RAW_REL_FAMILIA_AGRUPADOR AS PRFAF
        ON
            PRFAF.BAJA_LOGICA = 0
            AND PRFAF.CLA_ARTICULO <= 0
            AND PRFAF.CLA_SUBFAMILIA <= 0
            AND A.CLA_FAMILIA = PRFAF.CLA_FAMILIA
    LEFT JOIN
        RAW_CAT_FAMILIA_AGRUPADOR AS DESCFAE
        ON
            DESCFAE.CLA_FAMILIA_AGRUPADOR
            = COALESCE(
                COALESCE(
                    COALESCE(PRFA.CLA_FAM_AGRUPADOR, PRFASF.CLA_FAM_AGRUPADOR),
                    PRFAF.CLA_FAM_AGRUPADOR
                ),
                0
            )
    LEFT JOIN
        RAW_CAT_FAM_AGRUPADOR_DET AS DESCFAD
        ON
            DESCFAD.CLA_FAM_AGRUPADOR
            = COALESCE(
                COALESCE(
                    COALESCE(PRFA.CLA_FAM_AGRUPADOR, PRFASF.CLA_FAM_AGRUPADOR),
                    PRFAF.CLA_FAM_AGRUPADOR
                ),
                0
            )
            AND DESCFAD.CLA_FAMILIA_AGRUPADOR_DET
            = COALESCE(
                COALESCE(
                    COALESCE(
                        PRFA.CLA_FAM_AGRUPADOR_DET, PRFASF.CLA_FAM_AGRUPADOR_DET
                    ),
                    PRFAF.CLA_FAM_AGRUPADOR_DET
                ),
                0
            )
    LEFT JOIN
        RAW_REL_MERCADO_INV AS RMIA
        ON
            RMIA.BAJA_LOGICA = 0
            AND RMIA.CLA_PRODUCTO > 0
            AND A.CLA_PRODUCTO = RMIA.CLA_PRODUCTO
    LEFT JOIN
        RAW_REL_MERCADO_INV AS RMISF
        ON
            RMISF.BAJA_LOGICA = 0
            AND RMISF.CLA_PRODUCTO <= 0
            AND RMISF.CLA_SUBFAMILIA > 0
            AND A.CLA_SUBFAMILIA = RMISF.CLA_SUBFAMILIA
            AND A.CLA_FAMILIA = RMISF.CLA_FAMILIA
    LEFT JOIN
        RAW_REL_MERCADO_INV AS RMIF
        ON
            RMIF.BAJA_LOGICA = 0
            AND RMIF.CLA_PRODUCTO <= 0
            AND RMIF.CLA_SUBFAMILIA <= 0
            AND A.CLA_FAMILIA = RMIF.CLA_FAMILIA
    LEFT JOIN
        RAW_CAT_MERCADO_INV AS DESCRMI
        ON
            DESCRMI.CLA_MERCADO_INVENTARIO
            = COALESCE(
                COALESCE(
                    COALESCE(RMIA.CLA_MERCADO_INV, RMISF.CLA_MERCADO_INV),
                    RMIF.CLA_MERCADO_INV
                ),
                0
            )
--MAES EG


    LEFT JOIN RAW_REL_GPOEST_OFERTA_VALOR GpoEOV4			ON	GpoEOV4.NIVEL = 4		AND	GE4.CLA_GRUPO_ESTADISTICO = GpoEOV4.CLA_GPO_EST		
    LEFT JOIN RAW_REL_GPOEST_OFERTA_VALOR GpoEOV3			ON	GpoEOV3.NIVEL = 3		AND	GE3.CLA_GRUPO_ESTADISTICO = GpoEOV3.CLA_GPO_EST
    LEFT JOIN RAW_REL_GPOEST_OFERTA_VALOR GpoEOV2			ON	GpoEOV2.NIVEL = 2		AND	GE2.CLA_GRUPO_ESTADISTICO = GpoEOV2.CLA_GPO_EST
    LEFT JOIN RAW_REL_GPOEST_OFERTA_VALOR GpoEOV1			ON	GpoEOV1.NIVEL = 1		AND	GE1.CLA_GRUPO_ESTADISTICO = GpoEOV1.CLA_GPO_EST

    LEFT JOIN RAW_CAT_OFERTA_VALOR OV					ON	OV.CLA_OFERTA_VALOR =	
																				IFNULL(GpoEOV4.CLA_OFERTA_VALOR,
																					IFNULL(GpoEOV3.CLA_OFERTA_VALOR,
																						IFNULL(GpoEOV2.CLA_OFERTA_VALOR,
																							IFNULL(GpoEOV1.CLA_OFERTA_VALOR,-1))))

)

SELECT * FROM MST_PRODUCTO_VW
