{{ config(materialized='table') }}

WITH
MST_PARIDAD_VW AS (
    SELECT
        FECHAPARIDAD AS FECHA_PARIDAD,
        CLAMONEDA AS CLA_MONEDA,
        PARIDADMONEDAPESO AS PARIDAD_MONEDA_PESO,
        PARIDADMONEDADOLAR AS PARIDAD_MONEDA_DOLAR,
        PARIDADDOLARMON AS PARIDAD_DOLAR_MON
    FROM {{ ref('stg__con_cat_paridad') }}
)

SELECT * FROM MST_PARIDAD_VW
