{{ config(materialized='table') }}
WITH
RAW_CAT_CLIENTE_CUENTA
AS
(
	SELECT
			CLACLIENTECUENTA	AS CLA_CLIENTE,
			NOMCLIENTECUENTA	AS NOM_CLIENTE,
			CLACLIENTEUNICO	AS CLA_CLIENTE_UNICO,
			CLAZONA	AS CLA_ZONA,
			FECHAALTA	AS FECHA_ALTA_CUENTA,
			FECHABAJALOGICA	AS FECHA_BAJA_CUENTA,
			CLANIVELCANAL	AS CLA_NIVEL_CANAL,
			CLAAGENTE	AS CLA_AGENTE,
			CLAESTATUSCLIENTE	AS CLA_ESTATUS_CLIENTE,
			CLAIVA	AS TASA_IVA,
			CLACIUDADUNICO	AS CLA_CIUDAD_UNICO,
			CLAMARCA	AS CLA_MARCA,
			CLAGIROINDUSTRIA	AS CLA_GIRO_INDUSTRIA,
			CLAGIROCOMERCIAL	AS CLA_GIRO_COMERCIAL,
			CLACATEGORIACLIENTE	AS CLA_CATEGORIA_CLIENTE,
			CLATIPOCLIENTE	AS CLA_TIPO_CLIENTE
	FROM {{ref('stg__vta_cat_cliente_cuenta')}}
),
RAW_CAT_CLIENTE_UNICO
AS
(
	SELECT
			CLACLIENTEUNICO	AS CLA_CLIENTE_UNICO,
			nomclienteunico AS NOM_CLIENTE_UNICO,
			RFC,
			esfilialdeacero	AS ES_FILIAL_DEACERO,--ESTO DEBERIA IR AQUI ?
			FECHAALTA	AS FECHA_ALTA_CUC,
			FECHABAJALOGICA	AS FECHA_BAJA_CUC,
			CLANIVELCANAL	AS CLA_NIVEL_CANAL_CUC,
			CLAGIROMASTER	AS CLA_GIRO_MASTER_CUC,
			CLANIVELOFERTANUEVA	AS CLA_NIVEL_OFERTA_NUEVA_CUC,
			CLACIUDADUNICO	AS CLA_CIUDAD_UNICO,
			CLAAGRUPADORCLIENTEUNICO	AS CLA_AGRUPADOR_CLIENTE_UNICO,
			CLATIPOOPERACION	AS CLA_TIPO_OPERACION,
			CLATIPOPROVEEDOR	AS CLA_TIPO_PROVEEDOR,
			CLATIPOPERSONA	AS CLA_TIPO_PERSONA,
			CLAPRIORIZACION	AS CLA_PRIORIZACION,
            clatipoportafolio as CLA_TIPO_PORTAFOLIO,
    FROM {{ref('int__dcp_vta_cat_cliente_unico')}}
),

RAW_CAT_AGRUPADOR_CLIENTE_UNICO
AS
(
	SELECT
			CLAAGRUPADORCLIENTEUNICO	AS CLA_AGRUPADOR_CLIENTE_UNICO,
			NOMAGRUPADORCLIENTEUNICO	AS NOM_AGRUPADOR_CLIENTE_UNICO
	FROM {{ref('stg__vta_cat_agrupador_cliente_unico')}}
),

MST_CIUDAD
AS
(
	SELECT
			CLA_CIUDAD_UNICO	AS CLA_CIUDAD,
			NOM_CIUDAD	AS NOM_CIUDAD,
			CLA_ESTADO	AS CLA_ESTADO,
			NOM_ESTADO AS NOM_ESTADO,
			CLA_PAIS	AS CLA_PAIS,
			NOM_PAIS	AS NOM_PAIS
	FROM {{ref('con__ciudad')}}
),

RAW_CAT_NIVEL_CANAL
AS
(
	SELECT
			CLANIVELCANAL	AS CLA_NIVEL_CANAL,
			NOMNIVELCANAL	AS NOM_CANAL
	FROM {{ref('stg__vta_cat_nivel_canal')}}
),

RAW_CAT_MARCA
AS
(
	SELECT
			CLAMARCA	AS CLA_MARCA,
			UPPER(NOMMARCA)	AS NOM_MARCA
	FROM {{ref('stg__vta_cat_marca')}}--pendiente de enlazar a la tabla final que apunta al new dataset
),

RAW_CAT_GIRO_INDUSTRIAL
AS
(
	SELECT
			CLAGIROINDUSTRIA	AS CLA_GIRO_INDUSTRIA,
			NOMBREGIROINDUSTRIA	AS NOM_GIRO_INDUSTRIA,
			NOMBREGIROINDUSTRIAING AS NOM_GIRO_INDUSTRIA_EN
	FROM {{ref('stg__vta_cat_giro_industria')}}
),

RAW_CAT_GIRO_COMERCIAL
AS
(
	SELECT
			CLAGIROCOMERCIAL	AS CLA_GIRO_COMERCIAL,
			NOMBREGIROCOMERCIAL	AS NOM_GIRO_COMERCIAL,
			NOMBREGIROCOMERCIALING	AS NOM_GIRO_COMERCIAL_EN
	FROM {{ref('stg__vta_cat_giro_comercial')}}
),

RAW_CAT_CATEGORIA_CLIENTE
AS
(
	SELECT
			CLACATEGORIACLIENTE	AS CLA_CATEGORIA_CLIENTE,
			NOMCATEGORIACLIENTE	AS NOM_CATEGORIA_CLIENTE,
			NOMCATEGORIACLIENTEING	AS NOM_CATEGORIA_CLIENTE_EN
	FROM {{ref('stg__vta_cat_categoria_cliente')}}
),

RAW_CAT_TIPO_CLIENTE
AS
(
	SELECT
			CLATIPOCLIENTE	AS CLA_TIPO_CLIENTE,
			NOMTIPOCLIENTE	AS NOM_TIPO_CLIENTE,
			NOMTIPOCLIENTEING	AS NOM_TIPO_CLIENTE_EN
	FROM {{ref('stg__vta_cat_tipo_cliente')}}
),

RAW_CAT_TIPO_OPERACION
AS
(
	SELECT
			CLATIPOOPERACION	AS CLA_TIPO_OPERACION,
			NOMTIPOOPERACION	AS NOM_TIPO_OPERACION,
			NOMTIPOOPERACIONING	AS NOM_TIPO_OPERACION_EN
	FROM {{ref('stg__vta_cat_tipo_operacion')}}
),

RAW_CAT_TIPO_PROVEEDOR
AS
(
	SELECT
			CLATIPOPROVEEDOR	AS CLA_TIPO_PROVEEDOR,
			NOMTIPOPROVEEDOR	AS NOM_TIPO_PROVEEDOR,
			NOMTIPOPROVEEDOREN	AS NOM_TIPO_PROVEEDOR_EN
	FROM {{ref('stg__fis_cat_tipo_proveedor')}}
),

RAW_CAT_TIPO_PERSONA
AS
(
	SELECT
			CLATIPOPERSONA	AS CLA_TIPO_PERSONA,
			NOMTIPOPERSONA	AS NOM_TIPO_PERSONA,
			NOMTIPOPERSONAEN	AS NOM_TIPO_PERSONA_EN
	FROM {{ref('stg__fis_cat_tipo_persona')}}
),

RAW_CAT_AGENTE_WT
AS
(
	SELECT
			claagente	AS CLA_AGENTE,
			nomagentecompleto AS NOM_AGENTE
	FROM {{ref('int__dcp_vta_cat_agente_wt')}}
),
MST_CIUDAD_CUC
AS
(
	SELECT
			CLA_CIUDAD_UNICO	AS CLA_CIUDAD_CUC,
			NOM_CIUDAD	AS NOM_CIUDAD_CUC,
			CLA_ESTADO	AS CLA_ESTADO_CUC,
			NOM_ESTADO	AS NOM_ESTADO_CUC,
			CLA_PAIS	AS CLA_PAIS_CUC,
			NOM_PAIS	AS NOM_PAIS_CUC
	FROM {{ref('con__ciudad')}} 
),
RAW_CAT_PRIORIZACION_CUC
AS
(
	SELECT
			CLAPRIORIZACION	AS CLA_PRIORIZACION,
			(NOMPRIORIZACION)	AS NOM_PRIORIZACION
	FROM {{ref('stg__vta_cat_priorizacion_cuc')}}
),

RAW_CAT_NIVEL_CANAL_CUC
AS
(
	SELECT
			CLANIVELCANAL	AS CLA_NIVEL_CANAL,
			NOMNIVELCANAL	AS NOM_NIVEL_CANAL_CUC
	FROM {{ref('stg__vta_cat_nivel_canal')}}
),

RAW_CAT_GIRO_MASTER_CUC
AS
(
	SELECT
			CLAGIROMASTER	AS CLA_GIRO_MASTER,
			NOMGIROMASTER	AS NOM_GIRO_MASTER_CUC
	FROM {{ref('stg__vta_cat_giro_master')}}
),

RAW_CAT_NIVEL_OFERTA_NUEVA_CUC
AS
(
	SELECT
			CLANIVELOFERTANUEVA	AS CLA_NIVEL_OFERTA_NUEVA,
			(NOMNIVELOFERTANUEVA)	AS NOM_NIVEL_OFERTA_NUEVA_CUC
	FROM {{ref('stg__vta_cat_nivel_oferta_nueva')}}
),

RAW_CAT_ESTATUS_CLIENTE
AS
(
	SELECT
			CLAESTATUSCLIENTE	AS CLA_ESTATUS_CLIENTE,
			(NOMESTATUSCLIENTE)	AS NOM_ESTATUS_CLIENTE
	FROM {{ref('stg__vta_cat_estatus_cliente')}}
),

RAW_TRA_ESTATUS_CARTERA_CLIENTE2_CUC
AS
(
	SELECT
			CLACLIENTEUNICO	AS CLA_CLIENTE_UNICO,
			nomestatuscarteracuc	AS NOM_ESTATUS_CARTERA_CUC,
			ESTATUSFINAL	AS CLA_ESTATUS_CARTERA_CUC
	FROM {{ref('int__dcp_vta_tra_estatus_cartera_cliente2')}}
),
MST_ORGANIZACION_VTA
AS
(
	SELECT
			CLA_ZONA,
			NOM_ZONA,
			CLA_GERENCIA,
			NOM_GERENCIA,
			CLA_GERENCIA_REGIONAL,
			NOM_GERENCIA_REGIONAL,
			cla_sub_direccion as CLA_SUBDIRECCION,
			nom_sub_direccion as NOM_SUBDIRECCION,
			CLA_DIRECCION,
			NOM_DIRECCION,
			CLA_GRUPO,
			NOM_GRUPO,
			NIVEL
	FROM {{ref('con__organizacion')}}--En hold a falta de tablas PREPARE ALINA HERE BANDERA
),


--Tablas de MAES
RAW_CAT_TIPO_PORTAFOLIO
AS
(
	SELECT
            ClaTipoPortafolio,
            NomTipoPortafolio,
	FROM {{ref('stg_vta_cat_tipo_portafolio')}}
),

RAW_MODELO_ATENCION_NIVEL_CANAL
AS
(
	SELECT
        ClaNivelCanal,
        ClaUsuarioMod,
        FechaUltimaMod,
        FechaBajaLogica,
        ClaModeloAtencion,
	FROM {{ref('stg_vta_rel_modelo_atencion_nivel_canal')}}
),

RAW_MODELO_ATENCION
AS
(

	SELECT 

         BajaLogica,
         Descripcion,
         NombrePcMod,
         ClaUsuarioMod,
         FechaUltimaMod,
         FechaBajaLogica,
         ClaModeloAtencion,
         NomModeloAtencion,
         
	FROM {{ref('stg_vta_cat_modelo_atencion')}}
),
MST_CLIENTE_VW
AS
(
	SELECT
			CC.CLA_CLIENTE,
			CC.NOM_CLIENTE,
			CC.CLA_CLIENTE_UNICO,
			CU.NOM_CLIENTE_UNICO,
			ACU.CLA_AGRUPADOR_CLIENTE_UNICO,
			ACU.NOM_AGRUPADOR_CLIENTE_UNICO,
			CC.CLA_ZONA,
			O.NOM_ZONA,
			O.CLA_GERENCIA,
			O.NOM_GERENCIA,
			O.CLA_GERENCIA_REGIONAL,
			O.NOM_GERENCIA_REGIONAL,
			O.CLA_SUBDIRECCION,
			O.NOM_SUBDIRECCION,
			O.CLA_DIRECCION,
			O.NOM_DIRECCION,
			O.CLA_GRUPO,
			O.NOM_GRUPO,
			CIU.CLA_CIUDAD,
			CIU.NOM_CIUDAD,
			CIU.CLA_ESTADO,
			CIU.NOM_ESTADO,
			CIU.CLA_PAIS,
			CIU.NOM_PAIS,
			CU.RFC,
			CU.ES_FILIAL_DEACERO,
			CC.FECHA_ALTA_CUENTA,
			CC.FECHA_BAJA_CUENTA,
			CU.FECHA_ALTA_CUC,
			CU.FECHA_BAJA_CUC,
			CC.CLA_NIVEL_CANAL,
			NC.NOM_CANAL,
			M.CLA_MARCA,
			M.NOM_MARCA,
			GI.CLA_GIRO_INDUSTRIA,
			GI.NOM_GIRO_INDUSTRIA,
			GI.NOM_GIRO_INDUSTRIA_EN,
			GC.CLA_GIRO_COMERCIAL,
			GC.NOM_GIRO_COMERCIAL,
			GC.NOM_GIRO_COMERCIAL_EN,
			CATC.CLA_CATEGORIA_CLIENTE,
			CATC.NOM_CATEGORIA_CLIENTE,
			CATC.NOM_CATEGORIA_CLIENTE_EN,
			CTC.CLA_TIPO_CLIENTE,
			CTC.NOM_TIPO_CLIENTE,
			CTC.NOM_TIPO_CLIENTE_EN,
			CTO.CLA_TIPO_OPERACION,
			CTO.NOM_TIPO_OPERACION,
			CTO.NOM_TIPO_OPERACION_EN,
			PROV.CLA_TIPO_PROVEEDOR,
			PROV.NOM_TIPO_PROVEEDOR,
			PROV.NOM_TIPO_PROVEEDOR_EN,
			TP.CLA_TIPO_PERSONA,
			TP.NOM_TIPO_PERSONA,
			TP.NOM_TIPO_PERSONA_EN,
			CC.CLA_AGENTE,
			AG.NOM_AGENTE,
			CC.TASA_IVA,
			CIUCUC.CLA_CIUDAD_CUC,
			CIUCUC.NOM_CIUDAD_CUC,
			CIUCUC.CLA_ESTADO_CUC,
			CIUCUC.NOM_ESTADO_CUC,
			CIUCUC.CLA_PAIS_CUC,
			CIUCUC.NOM_PAIS_CUC,
			PRI.CLA_PRIORIZACION,
			PRI.NOM_PRIORIZACION,
			CU.CLA_NIVEL_CANAL_CUC,
			NCC.NOM_NIVEL_CANAL_CUC,
			CU.CLA_GIRO_MASTER_CUC,
			GMC.NOM_GIRO_MASTER_CUC,
			EC.CLA_ESTATUS_CARTERA_CUC,
			EC.NOM_ESTATUS_CARTERA_CUC,
			CU.CLA_NIVEL_OFERTA_NUEVA_CUC,
			OFN.NOM_NIVEL_OFERTA_NUEVA_CUC,
			CC.CLA_ESTATUS_CLIENTE,
			ESC.NOM_ESTATUS_CLIENTE,
--MAES
            (MA.ClaModeloAtencion= IFNULL(MA.ClaModeloAtencion,-1)) as CLAMODELOATENCION ,					
            (MA.NomModeloAtencion= IFNULL(MA.NomModeloAtencion,'OTROS')) as NOMBREMODELOATENCION,	
            (CU.CLA_TIPO_PORTAFOLIO	= IFNULL(TPortafolio.ClaTipoPortafolio,-1)) as CLATIPOPORTAFOLIO,				
            (TPortafolio.NomTipoPortafolio= IFNULL(TPortafolio.NomTipoPortafolio,'OTROS')) as NOMTIPOPORTAFOLIO,


	FROM RAW_CAT_CLIENTE_CUENTA CC	
	LEFT JOIN MST_ORGANIZACION_VTA O ON O.CLA_ZONA = CC.CLA_ZONA AND O.NIVEL = 50
	LEFT JOIN RAW_CAT_CLIENTE_UNICO CU ON CC.CLA_CLIENTE_UNICO = CU.CLA_CLIENTE_UNICO
	LEFT JOIN MST_CIUDAD CIU ON CC.CLA_CIUDAD_UNICO = CIU.CLA_CIUDAD
	LEFT JOIN MST_CIUDAD_CUC CIUCUC ON CU.CLA_CIUDAD_UNICO = CIUCUC.CLA_CIUDAD_CUC
	LEFT JOIN RAW_CAT_AGRUPADOR_CLIENTE_UNICO ACU ON CU.CLA_AGRUPADOR_CLIENTE_UNICO = ACU.CLA_AGRUPADOR_CLIENTE_UNICO
	LEFT JOIN RAW_CAT_MARCA M ON M.CLA_MARCA = CC.CLA_MARCA
	LEFT JOIN RAW_CAT_GIRO_INDUSTRIAL GI ON GI.CLA_GIRO_INDUSTRIA = CC.CLA_GIRO_INDUSTRIA
	LEFT JOIN RAW_CAT_GIRO_COMERCIAL GC ON GC.CLA_GIRO_COMERCIAL = CC.CLA_GIRO_COMERCIAL
	LEFT JOIN RAW_CAT_NIVEL_CANAL NC ON CC.CLA_NIVEL_CANAL = NC.CLA_NIVEL_CANAL
	LEFT JOIN RAW_CAT_NIVEL_CANAL_CUC NCC ON CU.CLA_NIVEL_CANAL_CUC = NCC.CLA_NIVEL_CANAL
	LEFT JOIN RAW_CAT_GIRO_MASTER_CUC GMC ON CU.CLA_GIRO_MASTER_CUC = GMC.CLA_GIRO_MASTER
	LEFT JOIN RAW_CAT_CATEGORIA_CLIENTE CATC ON CATC.CLA_CATEGORIA_CLIENTE = CC.CLA_CATEGORIA_CLIENTE
	LEFT JOIN RAW_CAT_TIPO_CLIENTE CTC ON CTC.CLA_TIPO_CLIENTE = CC.CLA_TIPO_CLIENTE
	LEFT JOIN RAW_CAT_TIPO_OPERACION CTO ON CTO.CLA_TIPO_OPERACION = CU.CLA_TIPO_OPERACION
	LEFT JOIN RAW_CAT_TIPO_PROVEEDOR PROV ON CU.CLA_TIPO_PROVEEDOR = PROV.CLA_TIPO_PROVEEDOR
	LEFT JOIN RAW_CAT_TIPO_PERSONA TP ON TP.CLA_TIPO_PERSONA = CU.CLA_TIPO_PERSONA
	LEFT JOIN RAW_CAT_AGENTE_WT AG ON AG.CLA_AGENTE = CC.CLA_AGENTE
	LEFT JOIN RAW_CAT_PRIORIZACION_CUC PRI ON PRI.CLA_PRIORIZACION = CU.CLA_PRIORIZACION
	LEFT JOIN RAW_TRA_ESTATUS_CARTERA_CLIENTE2_CUC EC ON EC.CLA_CLIENTE_UNICO = CU.CLA_CLIENTE_UNICO
	LEFT JOIN RAW_CAT_NIVEL_OFERTA_NUEVA_CUC OFN ON OFN.CLA_NIVEL_OFERTA_NUEVA = CU.CLA_NIVEL_OFERTA_NUEVA_CUC
	LEFT JOIN RAW_CAT_ESTATUS_CLIENTE ESC ON CC.CLA_ESTATUS_CLIENTE = ESC.CLA_ESTATUS_CLIENTE

    LEFT JOIN RAW_MODELO_ATENCION_NIVEL_CANAL MANC		ON CC.CLA_NIVEL_CANAL = MANC.ClaNivelCanal
    LEFT JOIN RAW_MODELO_ATENCION MA ON MANC.ClaModeloAtencion = MA.ClaModeloAtencion
    LEFT JOIN RAW_CAT_TIPO_PORTAFOLIO TPortafolio ON CU.CLA_TIPO_PORTAFOLIO = TPortafolio.ClaTipoPortafolio


)
SELECT * FROM MST_CLIENTE_VW
