{{ config(materialized='table') }}

WITH
RAW_CON_CAT_EMPRESA AS (
    SELECT
        CLAEMPRESA AS CLA_EMPRESA,
        NOMCORTOEMPRESA AS NOM_EMPRESA
    FROM {{ ref('stg__con_cat_empresa') }}
),

RAW_FIS_CAT_INFORMACION_FISCAL_EMPRESA AS (
    SELECT
        RFC AS CLA_RFC,
        CLAEMPRESA AS CLA_EMPRESA
    FROM {{ ref('stg__fis_cat_informacion_fiscal_empresa') }}
),

MST_EMPRESA_VW AS (
    SELECT
        RAW_CON_CAT_EMPRESA.CLA_EMPRESA,
        RAW_CON_CAT_EMPRESA.NOM_EMPRESA,
        RAW_FIS_CAT_INFORMACION_FISCAL_EMPRESA.CLA_RFC
    FROM RAW_CON_CAT_EMPRESA
    LEFT JOIN
        RAW_FIS_CAT_INFORMACION_FISCAL_EMPRESA
        ON
            RAW_CON_CAT_EMPRESA.CLA_EMPRESA
            = RAW_FIS_CAT_INFORMACION_FISCAL_EMPRESA.CLA_EMPRESA
)

SELECT * FROM MST_EMPRESA_VW
