{{ config(materialized='table') }}
WITH DEPARTAMENTO AS (
    SELECT DISTINCT
        G.CLAGPOPOLIZA AS CLADEPARTAMENTO,
        R.CLAEMPRESA,
        G.NOMGPOPOLIZA AS NOMDEPARTAMENTO,
        G.CLABENEFICIARIO,
        D.NUMDIRECCION AS CLADIRECCION,
        G.BAJALOGICA,
        G.FECHABAJALOGICA,
        G.CLAUSUARIOMOD,
        NOMGPOPOLIZA2 AS NOMDEPARTAMENTO2,
        NOMGPOPOLIZA3 AS NOMDEPARTAMENTO3,
        NOMGPOPOLIZA4 AS NOMDEPARTAMENTO4,
        NOMGPOPOLIZA5 AS NOMDEPARTAMENTO5,
        CASE
            WHEN
                G.FECHAULTIMAMOD > R.FECHAULTIMAMOD
                THEN G.FECHAULTIMAMOD
        ELSE R.FECHAULTIMAMOD
        END AS FECHAULTIMAMOD
    FROM {{ ref('stg__con_cat_gpo_poliza') }} AS G
    INNER JOIN
        {{ ref('stg__con_cat_direccion') }} AS D
        ON G.CLADIRECCION = D.CLADIRECCION
    INNER JOIN
        {{ ref('stg__con_rel_direccion_empresa') }}
            AS R
        ON G.CLADIRECCION = R.CLADIRECCION
),

MST_CAT_DEPARTAMENTO AS (
    SELECT DISTINCT
        CLADEPARTAMENTO AS CLA_DEPARTAMENTO,
        NOMDEPARTAMENTO AS NOM_DEPARTAMENTO
    FROM DEPARTAMENTO
)

SELECT * FROM MST_CAT_DEPARTAMENTO
