{{ config(materialized='table') }}

WITH
RAW_CAT_CONSIGNADO AS (
    SELECT
        CLACLIENTEUNICO AS CLA_CLIENTE_UNICO,
        CLACIUDADUNICO AS CLA_CIUDAD_UNICO,
        CLACONSIGNADO AS CLA_CONSIGNADO,
        NOMBRECONSIGNADO AS NOM_CONSIGNADO,
        FECHAALTA AS FECHA_ALTA,
        FECHABAJALOGICA AS FECHA_BAJA_LOGICA
    FROM {{ ref('stg__vta_cat_consignado') }}
),

MST_CIUDAD AS (
    SELECT
        CLA_CIUDAD_UNICO AS CLA_CIUDAD_CONSIGNADO,
        NOM_CIUDAD AS NOM_CIUDAD_CONSIGNADO,
        CLA_ESTADO AS CLA_ESTADO_CONSIGNADO,
        NOM_ESTADO AS NOM_ESTADO_CONSIGNADO,
        CLA_PAIS AS CLA_PAIS_CONSIGNADO,
        NOM_PAIS AS NOM_PAIS_CONSIGNADO
    FROM {{ ref('con__ciudad') }}
),

RAW_CAT_CONSIGNADOGLP AS (
    SELECT
        CLACONSIGNADO AS CLA_CONSIGNADO,
        LATITUD,
        LONGITUD
    FROM {{ ref('stg__vta_cat_consignado_glp') }}
),

RAW_CAT_CONSIGNADO_CLIENTE_UNICO AS (
    SELECT
        CLACONSIGNADO AS CLA_CONSIGNADO,
        MAX(CLACLIENTEUNICO) AS CLA_CLIENTE_UNICO
    FROM {{ ref('stg__vta_cat_consignado') }}
    GROUP BY CLACONSIGNADO
),

RAW_CAT_CONSIGNADO_CIUDAD_UNICO AS (
    SELECT CLACONSIGNADO AS CLA_CONSIGNADO
    FROM {{ ref('stg__vta_cat_consignado') }}
    GROUP BY CLACONSIGNADO
    HAVING COUNT(DISTINCT CLACIUDADUNICO) > 1
),

MST_CONSIGNADO_VW AS (
    SELECT
        C.CLA_CONSIGNADO,
        C.NOM_CONSIGNADO,
        CIU.CLA_CIUDAD_CONSIGNADO,
        CIU.NOM_CIUDAD_CONSIGNADO,
        CIU.CLA_ESTADO_CONSIGNADO,
        CIU.NOM_ESTADO_CONSIGNADO,
        CIU.CLA_PAIS_CONSIGNADO,
        CIU.NOM_PAIS_CONSIGNADO,
        CG.LATITUD,
        CG.LONGITUD,
        C.FECHA_ALTA,
        C.FECHA_BAJA_LOGICA
    FROM RAW_CAT_CONSIGNADO AS C
    INNER JOIN
        RAW_CAT_CONSIGNADO_CLIENTE_UNICO AS C1
        ON
            C.CLA_CONSIGNADO = C1.CLA_CONSIGNADO
            AND C.CLA_CLIENTE_UNICO = C1.CLA_CLIENTE_UNICO
    LEFT JOIN
        MST_CIUDAD AS CIU
        ON C.CLA_CIUDAD_UNICO = CIU.CLA_CIUDAD_CONSIGNADO
    LEFT JOIN
        RAW_CAT_CONSIGNADOGLP AS CG
        ON C.CLA_CONSIGNADO = CG.CLA_CONSIGNADO
    WHERE
        C.CLA_CONSIGNADO NOT IN (
            SELECT CLA_CONSIGNADO FROM RAW_CAT_CONSIGNADO_CIUDAD_UNICO
        )

)

SELECT * FROM MST_CONSIGNADO_VW
