{{ config(materialized='table') }}

WITH RAW_CAT_ORGANIZACION_WT AS (
    SELECT
        CLAORGANIZACION AS CLA_ORGANIZACION,
        NIVEL,
        CLAGRUPO AS CLA_GRUPO,
        CLADIRECCION AS CLA_DIRECCION,
        CLASUBDIRECCION AS CLA_SUBDIRECCION,
        CLAGERENCIAREGIONAL AS CLA_GERENCIA_REGIONAL,
        CLAGERENCIA AS CLA_GERENCIA,
        CLAZONA AS CLA_ZONA,
        NOMORGANIZACION AS NOM_ORGANIZACION
    FROM {{ ref('stg__vta_cat_organizacion_wt') }}
),

RAW_CAT_ORGANIZACION_WT_GRUPO AS (
    SELECT
        CLAORGANIZACION AS CLA_ORGANIZACION,
        NOMORGANIZACION AS NOM_GRUPO
    FROM {{ ref('stg__vta_cat_organizacion_wt') }}
    WHERE NIVEL = 10
),

RAW_CAT_ORGANIZACION_WT_DIRECCION AS (
    SELECT
        CLAORGANIZACION AS CLA_ORGANIZACION,
        NOMORGANIZACION AS NOM_DIRECCION
    FROM {{ ref('stg__vta_cat_organizacion_wt') }}
    WHERE NIVEL = 20
),

RAW_CAT_ORGANIZACION_WT_SUBDIRECCION AS (
    SELECT
        CLAORGANIZACION AS CLA_ORGANIZACION,
        NOMORGANIZACION AS NOM_SUBDIRECCION
    FROM {{ ref('stg__vta_cat_organizacion_wt') }}
    WHERE NIVEL = 30
),

RAW_CAT_ORGANIZACION_WT_GERENCIA_REGIONAL AS (
    SELECT
        CLAORGANIZACION AS CLA_ORGANIZACION,
        NOMORGANIZACION AS NOM_GERENCIA_REGIONAL
    FROM {{ ref('stg__vta_cat_organizacion_wt') }}
    WHERE NIVEL = 40
),

RAW_CAT_ORGANIZACION_WT_GERENCIA AS (
    SELECT
        CLAORGANIZACION AS CLA_ORGANIZACION,
        NOMORGANIZACION AS NOM_GERENCIA
    FROM {{ ref('stg__vta_cat_organizacion_wt') }}
    WHERE NIVEL = 45
),

RAW_CAT_ORGANIZACION_WT_ZONA AS (
    SELECT
        CLAORGANIZACION AS CLA_ORGANIZACION,
        NOMORGANIZACION AS NOM_ZONA
    FROM {{ ref('stg__vta_cat_organizacion_wt') }}
    WHERE NIVEL = 50
),

MST_ORGANIZACION_VTA_VW AS (
    SELECT
        RAW_CAT_ORGANIZACION_WT.CLA_ORGANIZACION,
        RAW_CAT_ORGANIZACION_WT.NIVEL,
        RAW_CAT_ORGANIZACION_WT.NOM_ORGANIZACION,
        RAW_CAT_ORGANIZACION_WT.CLA_GRUPO,
        RAW_CAT_ORGANIZACION_WT_GRUPO.NOM_GRUPO,
        RAW_CAT_ORGANIZACION_WT.CLA_DIRECCION,
        RAW_CAT_ORGANIZACION_WT_DIRECCION.NOM_DIRECCION,
        RAW_CAT_ORGANIZACION_WT.CLA_SUBDIRECCION,
        RAW_CAT_ORGANIZACION_WT_SUBDIRECCION.NOM_SUBDIRECCION,
        RAW_CAT_ORGANIZACION_WT.CLA_GERENCIA_REGIONAL,
        RAW_CAT_ORGANIZACION_WT_GERENCIA_REGIONAL.NOM_GERENCIA_REGIONAL,
        RAW_CAT_ORGANIZACION_WT.CLA_GERENCIA,
        RAW_CAT_ORGANIZACION_WT_GERENCIA.NOM_GERENCIA,
        RAW_CAT_ORGANIZACION_WT.CLA_ZONA,
        RAW_CAT_ORGANIZACION_WT_ZONA.NOM_ZONA
    FROM RAW_CAT_ORGANIZACION_WT
    LEFT JOIN
        RAW_CAT_ORGANIZACION_WT_GRUPO
        ON
            RAW_CAT_ORGANIZACION_WT.CLA_GRUPO
            = RAW_CAT_ORGANIZACION_WT_GRUPO.CLA_ORGANIZACION
    LEFT JOIN
        RAW_CAT_ORGANIZACION_WT_DIRECCION
        ON
            RAW_CAT_ORGANIZACION_WT.CLA_DIRECCION
            = RAW_CAT_ORGANIZACION_WT_DIRECCION.CLA_ORGANIZACION
    LEFT JOIN
        RAW_CAT_ORGANIZACION_WT_SUBDIRECCION
        ON
            RAW_CAT_ORGANIZACION_WT.CLA_SUBDIRECCION
            = RAW_CAT_ORGANIZACION_WT_SUBDIRECCION.CLA_ORGANIZACION
    LEFT JOIN
        RAW_CAT_ORGANIZACION_WT_GERENCIA_REGIONAL
        ON
            RAW_CAT_ORGANIZACION_WT.CLA_GERENCIA_REGIONAL
            = RAW_CAT_ORGANIZACION_WT_GERENCIA_REGIONAL.CLA_ORGANIZACION
    LEFT JOIN
        RAW_CAT_ORGANIZACION_WT_GERENCIA
        ON
            RAW_CAT_ORGANIZACION_WT.CLA_GERENCIA
            = RAW_CAT_ORGANIZACION_WT_GERENCIA.CLA_ORGANIZACION
    LEFT JOIN
        RAW_CAT_ORGANIZACION_WT_ZONA
        ON
            RAW_CAT_ORGANIZACION_WT.CLA_ZONA
            = RAW_CAT_ORGANIZACION_WT_ZONA.CLA_ORGANIZACION
)

SELECT * FROM MST_ORGANIZACION_VTA_VW
