WITH
MST_CLASIFICACION_PROYECTO_VW
AS
(
    SELECT
            CLACLASIFICACIONPROYECTO AS CLA_CLASIFICACION_PROYECTO,
            NOMCLASIFICACIONPROYECTO AS NOM_CLASIFICACION_PROYECTO
    FROM {{ref('stg__gpi_cat_clasificacion_proyecto')}}
)

SELECT * FROM MST_CLASIFICACION_PROYECTO_VW