{{config(materialized='table')}}
WITH
MST_AGRUPADOR_EMPRESA_VW
AS
(
    SELECT
            CLAAGRUPADOREMPRESA AS CLA_AGRUPADOR_EMPRESA,
            NOMAGRUPADOREMPRESA AS NOM_AGRUPADOR_EMPRESA
    FROM {{ref('int__dcp_cnt_cat_agrupador_empresa')}}
)

SELECT * FROM MST_AGRUPADOR_EMPRESA_VW