{{ config(materialized='table') }}

WITH MST_CATEGORIA_VW AS (
    SELECT
        CLACATEGORIA AS CLA_CATEGORIA,
        NOMCATEGORIAIDIOMA1 AS NOM_CATEGORIA_IDIOMA1,
        NOMCATEGORIAIDIOMA2 AS NOM_CATEGORIA_IDIOMA2,
        NOMCATEGORIAIDIOMA3 AS NOM_CATEGORIA_IDIOMA3,
        NOMCATEGORIAIDIOMA4 AS NOM_CATEGORIA_IDIOMA4,
        NOMCATEGORIAIDIOMA5 AS NOM_CATEGORIA_IDIOMA5,
        CLACATEGORIA1 AS CLA_CATEGORIA1,
        CLACATEGORIA2 AS CLA_CATEGORIA2,
        CLACATEGORIA3 AS CLA_CATEGORIA3,
        CLANIVELACTUAL AS CLA_NIVEL_ACTUAL,
        ESAFECTABLE AS ES_AFECTABLE,
        CLAAGRUPADORFINANCIERO AS CLA_AGRUPADOR_FINANCIERO
    FROM {{ ref('stg__con_cat_categoria') }}
)/*,

MST_CUENTA_CONTABLE_VW AS (
    SELECT
        CLACATEGORIA AS CLA_CATEGORIA,
        IDCUENTACONTABLE AS ID_CUENTA_CONTABLE
    FROM {{ ref('stg__con_tra_cuenta_contable') }}
),

CATEGORIA AS (
    SELECT
        CC.ID_CUENTA_CONTABLE AS CLA_CUENTA_UNICA,
        C1.CLA_CATEGORIA,
        C1.CLA_AGRUPADOR_FINANCIERO,
        C1.NOM_CATEGORIA_IDIOMA1 AS NOM_CATEGORIA,
        COALESCE(C2.CLA_CATEGORIA, C1.CLA_CATEGORIA1) AS CLA_CATEGORIA2,
        COALESCE(
            C2.NOM_CATEGORIA_IDIOMA1, C1.NOM_CATEGORIA_IDIOMA1
        ) AS NOM_CATEGORIA2,
        COALESCE(
            C3.CLA_CATEGORIA, COALESCE(C2.CLA_CATEGORIA, C1.CLA_CATEGORIA1)
        ) AS CLA_CATEGORIA3,
        COALESCE(
            C3.NOM_CATEGORIA_IDIOMA1, COALESCE(
                C2.NOM_CATEGORIA_IDIOMA1, C1.NOM_CATEGORIA_IDIOMA1
            )
        ) AS NOM_CATEGORIA3
    FROM MST_CATEGORIA_VW AS C1
    LEFT JOIN MST_CATEGORIA_VW AS C2
        ON (C1.CLA_CATEGORIA1 = C2.CLA_CATEGORIA AND C2.CLA_NIVEL_ACTUAL = 2)
    LEFT JOIN MST_CATEGORIA_VW AS C3
        ON (C2.CLA_CATEGORIA2 = C3.CLA_CATEGORIA AND C3.CLA_NIVEL_ACTUAL = 3)
    RIGHT JOIN MST_CUENTA_CONTABLE_VW AS CC
        ON (
            CC.CLA_CATEGORIA = COALESCE(
                C3.CLA_CATEGORIA, COALESCE(C2.CLA_CATEGORIA, C1.CLA_CATEGORIA1)
            )
        )
    WHERE
        C1.CLA_NIVEL_ACTUAL = 1
        AND CC.CLA_CATEGORIA <> 1
)*/

SELECT * FROM MST_CATEGORIA_VW
