{{config(materialized='table')}}
WITH
MST_AGRUPADOR_FINANCIERO_VW
AS
(
    SELECT
            CLAAGRUPADORFINANCIERO                  AS CLA_AGRUPADOR_FINANCIERO,
            NOMAGRUPADORFINANCIEROIDIOMA1    AS NOM_AGRUPADOR_FINANCIERO_IDIOMA1,
            NOMAGRUPADORFINANCIEROIDIOMA2    AS NOM_AGRUPADOR_FINANCIERO_IDIOMA2,
            NOMAGRUPADORFINANCIEROIDIOMA3    AS NOM_AGRUPADOR_FINANCIERO_IDIOMA3,
            NOMAGRUPADORFINANCIEROIDIOMA4    AS NOM_AGRUPADOR_FINANCIERO_IDIOMA4,
            NOMAGRUPADORFINANCIEROIDIOMA5    AS NOM_AGRUPADOR_FINANCIERO_IDIOMA5,
            ORDEN,
            ESRESULTADOINTEGRAL                     AS ES_RESULTADO_INTEGRAL,
            ESUTILIDADNETA                          AS ES_UTILIDAD_NETA,
            ESUTILIDADANTESIMPUESTOS                AS ES_UTILIDAD_ANTES_IMPUESTOS,
            ESRESULTADOFINANCIAMIENTO               AS ES_RESULTADO_FINANCIAMIENTO,
            ESOTROSGASTOS                           AS ES_OTROS_GASTOS,
            ESUTILIDADOPERACION                     AS ES_UTILIDAD_OPERACION,
            ESTOTALGASTOOPERACION                   AS ES_TOTAL_GASTO_OPERACION,
            ESUTILIDADBRUTA                         AS ES_UTILIDAD_BRUTA,
            ESACTIVOCIRCULANTE                      AS ES_ACTIVO_CIRCULANTE,
            ESACTIVONOCIRCULANTE                    AS ES_ACTIVO_NO_CIRCULANTE,
            ESACTIVOTOTAL                           AS ES_ACTIVO_TOTAL,
            ESPASIVOCORTOPLAZO                      AS ES_PASIVO_CORTO_PLAZO,
            ESPASIVOLARGOPLAZO                      AS ES_PASIVO_LARGO_PLAZO,
            ESPASIVOTOTAL                           AS ES_PASIVO_TOTAL,
            ESCAPITAL                               AS ES_CAPITAL,
            ESPASIVOMASCAPITAL                      AS ES_PASIVO_MAS_CAPITAL,
            FORMULAIMPORTE                          AS FORMULA_IMPORTE
    FROM {{ref('stg__con_cat_agrupador_financiero')}}
)

SELECT * FROM MST_AGRUPADOR_FINANCIERO_VW
